### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by mesflit** [termux/termux-x11#229] opened 2023-02-18 06:26 UTC
Mouse disappears when I open sonic.exe game

It would be nice to have such a feature.
Let's add buttons to the screen
So let's do our own checks
like this app
https://github.com/PojavLauncherTeam/PojavLauncher

**Comment by twaik** [comment] 2023-02-18 11:31
I am not sure but mouse disappears because some X client hides it. It is not a bug.
How Minecraft launcher is related to `termux-x11`???

**Comment by mesflit** [comment] 2023-02-18 14:38
> I am not sure but mouse disappears because some X client hides it. It is not a bug. How Minecraft launcher is related to `termux-x11`???

I meant the ability to add custom buttons to the screen in Pojavlauncher. I think it should be in termux-x11 app

**Comment by twaik** [comment] 2023-02-18 14:47
I am considering to add `termux-app`'s keyboard with it's ability to change keys. You will be able to use custom keys and remap them in your client...

**Comment by mesflit** [comment] 2023-02-18 14:53
> I am considering to add `termux-app`'s keyboard with it's ability to change keys. You will be able to use custom keys and remap them in your client...

When will this update come? sounds great

**Comment by twaik** [comment] 2023-02-18 15:01
I think soon. I am working on something that will make it possible.

**Comment by mesflit** [comment] 2023-02-21 13:26
> I think soon. I am working on something that will make it possible.

has it been added?

**Comment by twaik** [comment] 2023-02-21 13:28
Not yet. You will see a commit with corresponding description and I will close this issue.

**Comment by twaik** [comment] 2023-03-09 00:04
Fixed in https://github.com/termux/termux-x11/commit/cae6f0c91b5fbeeb5ab9f9fe4328e0e20f47528f .

**Closed by twaik** 2023-03-09 00:04 UTC
Labels: enhancement
