### ISSUE TITLE
Keyboard Not Working

### ISSUE THREAD

**Issue by ask9027** [termux/termux-x11#236] opened 2023-02-23 09:14 UTC
in latest build #233 onBackPressed.

**Comment by twaik** [comment] 2023-02-23 09:30
I checked it now. It works. `onBackPressed` asways was empty, back presses are dispatched in onKey.

**Comment by ask9027** [comment] 2023-02-23 09:51
here is short video about problem

https://user-images.githubusercontent.com/61283438/220872507-3200608f-314a-4c61-adb3-a66e9682008e.mp4

**Comment by twaik** [comment] 2023-02-23 10:24
Post `termux-info` output.

**Comment by ask9027** [comment] 2023-02-23 11:00
> 

[log.txt](https://github.com/termux/termux-x11/files/10812801/log.txt)

**Comment by twaik** [comment] 2023-02-23 11:07
I see here no criminal. Can you get logcat of `com.termux.x11`? And can you please try to invoke Hacker's keyboard from it's notification?

**Comment by ask9027** [comment] 2023-02-23 11:09
```
java.io.FileNotFoundException: /data/system/theme_config/theme_compatibility.xml: open failed: ENOENT (No such file or directory)
        at libcore.io.IoBridge.open(IoBridge.java:574)
        at java.io.FileInputStream.<init>(FileInputStream.java:160)
        at java.io.FileInputStream.<init>(FileInputStream.java:115)
        at java.io.FileReader.<init>(FileReader.java:60)
        at miui.content.res.ThemeCompatibilityLoader.getVersion(ThemeCompatibilityLoader.java:108)
        at miui.content.res.ThemeCompatibilityLoader.getConfigDocumentTree(ThemeCompatibilityLoader.java:126)
        at miui.content.res.ThemeCompatibilityLoader.loadConfig(ThemeCompatibilityLoader.java:59)
        at miui.content.res.ThemeCompatibility.<clinit>(ThemeCompatibility.java:31)
        at miui.content.res.ThemeCompatibility.isThemeEnabled(ThemeCompatibility.java:111)
        at android.content.res.MiuiResourcesImpl.<clinit>(MiuiResourcesImpl.java:41)
        at android.content.res.MiuiResources.<init>(MiuiResources.java:58)
        at android.content.res.IMiuiResourceImpl.createResources(IMiuiResourceImpl.java:13)
        at android.content.res.ThemeManagerStub.createMiuiResources(ThemeManagerStub.java:56)
        at android.content.res.Resources.getSystem(Resources.java:235)
        at android.app.ActivityManager.isHighEndGfx(ActivityManager.java:1084)
        at android.view.ThreadedRenderer.initForSystemProcess(ThreadedRenderer.java:217)
        at android.app.ActivityThread.systemMain(ActivityThread.java:7901)
        at com.termux.x11.Loader.main(Loader.java:37)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:363)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
        at libcore.io.IoBridge.open(IoBridge.java:560)
        ... 19 more
res = 0
Activity is started
Got getWaylandFD
{ParcelFileDescriptor: java.io.FileDescriptor@aa287e5}
Lorie requested fd
Got getLogFD
{ParcelFileDescriptor: java.io.FileDescriptor@cb9d2ba}
Got finish request
App sent finishing command
Starting Xwayland
```
keyboard also not working with gboard.

**Comment by ask9027** [comment] 2023-02-23 11:11
> I see here no criminal. Can you get logcat of `com.termux.x11`? And can you please try to invoke Hacker's keyboard from it's notification?

i dont have pc right now so i cant get logcat of termux-x11

**Comment by ask9027** [comment] 2023-02-23 11:49
here is the ```termux-x11``` cat log Lavel Error
[2023-02-23-17-15-35.txt](https://github.com/termux/termux-x11/files/10813161/2023-02-23-17-15-35.txt)
[2023-02-23-17-16-49.txt](https://github.com/termux/termux-x11/files/10813162/2023-02-23-17-16-49.txt)


i hope this will help

**Comment by twaik** [comment] 2023-02-23 11:56
Wow. I did not know there is a SIGSEGV. Thank you.

**Comment by ask9027** [comment] 2023-02-23 11:58
> Wow. I did not know there is a SIGSEGV. Thank you.

🙏

**Comment by Rhys-T** [comment] 2023-02-25 04:10
I'm having the same issue on a Samsung Tab S7+ running Android 13, after updating to [the latest build (#281)](https://github.com/termux/termux-x11/actions/runs/4264421988). Pressing the back button does nothing but make the device vibrate. If it helps, I can provide `termux-info` and `logcat` from my device too.

I tried the Hacker's Keyboard notification. Unfortunately, on this device, it always makes the keyboard flash open for a fraction of a second and then disappear again, unless I'm in something that 'should' accept keyboard input and would bring up the keyboard anyway, like the main Termux app or something. It has the same issue in Termux-X11. (I don't know if this is caused by changes in newer Android versions - HK hasn't been updated in a while, as far as I know - or by some of Samsung's customizations/One UI.)

Doing a binary search (and making sure to both install the .apk and `apt install --reinstall` the .deb each time), it looks like [build #269](https://github.com/termux/termux-x11/actions/runs/4246869415) is the last one where the back button brings up the keyboard, and [build #270](https://github.com/termux/termux-x11/actions/runs/4247516090) is the first one where it does nothing.

Hope this helps.

**Comment by twaik** [comment] 2023-03-01 22:40
Can you please check if it happens with latest build [here](https://github.com/twaik/termux-x11/actions)?

**Comment by Rhys-T** [comment] 2023-03-02 00:40
> [`termux-x11` not starting app, and app not starting `Xwayland`]

Got it. Just wanted to mention it, since it was different from how the previous builds seemed to work, and I wasn't sure if it was intentional or not.

> Try swipe down with three fingers. It is a new feature, I finished it 1 hour ago...

(Found that in #58 and replied there.)

> You can open preferences[…]

Thanks. I figured out that running the app without `Xwayland` would give me the button, but didn't think to check for a shortcut like that.

Is the notification gone on purpose? Without the notification, is there currently any way to shut down Termux:X11, short of force-stopping it and cleaning up the sockets? (Is it even supposed to be shut down, or is it supposed to just always be there?)

**Comment by twaik** [comment] 2023-03-02 10:44
> Got it. Just wanted to mention it, since it was different from how the previous builds seemed to work, and I wasn't sure if it was intentional or not.

Yeah, it was intentional. :)

> Is the notification gone on purpose? Without the notification, is there currently any way to shut down Termux:X11, short of force-stopping it and cleaning up the sockets? (Is it even supposed to be shut down, or is it supposed to just always be there?)

Yeah, it is gone on purpose. It seems to be annoying when there are two pinned notifications in status bar (1 from com.termux and 1 more from com.termux.x11) so I got rid of it. Since it does not hold compositor you can simply close it like regular app with swipe up from recents screen. But if you want to kill compositor you should do something like `pkill Xwayland` and `termux-x11` will close itself (it tracks Xwayland state if it is not launched detached). But you should now that sometimes Xwayland stays alive even after `pkill -9 Xwayland` and in this case you must force-stop com.termux app to kill it.

**Comment by twaik** [comment] 2023-03-02 11:08
Is a problem solved? Can I close the issue?

**Comment by ask9027** [comment] 2023-03-02 11:58
This [build](https://github.com/twaik/termux-x11/actions/runs/4313205238) working fine except two finger scrolling.

**Comment by twaik** [comment] 2023-03-02 12:02
What is wrong with two finger scrolling?

**Comment by ask9027** [comment] 2023-03-02 12:04
https://user-images.githubusercontent.com/61283438/222423039-37382381-201f-42e7-b837-e0c203866196.mp4

**Comment by twaik** [comment] 2023-03-02 12:12
Yeah, you are definitely right, I did not find out how to make scroll with XTest extension...

**Comment by ask9027** [comment] 2023-03-02 12:36
i install it fresh. but when i open, it is not asking `Run in termux Environment` Permission.
does it is not necessary now?

**Comment by twaik** [comment] 2023-03-02 12:37
No in current builds. But it will ask for it after merging to `termux/termux-x11`.

**Comment by ask9027** [comment] 2023-03-02 12:38
> No in current builds. But it will ask for it after merging to `termux/termux-x11`.
Oh, Okay

**Comment by ask9027** [comment] 2023-03-02 12:39
> Yeah, you are definitely right, I did not find out how to make scroll with XTest extension...

Look [this](https://stackoverflow.com/questions/10353948/fake-mouse-scroll-using-xtest-lib). is it helpful?

**Comment by twaik** [comment] 2023-03-02 12:41
I need to do this with libxcb, not xlib...

**Comment by twaik** [comment] 2023-03-02 13:30
Looks like I found it. So stupid, I was sending XCB_KEY_PRESS and wondering why it does not work. Check latest build in my fork.

**Comment by ask9027** [comment] 2023-03-02 13:37
> Looks like I found it. So stupid, I was sending XCB_KEY_PRESS and wondering why it does not work. Check latest build in my fork.

Fantastic 👍 it works. Please close this issue also.

**Closed** 2023-03-02 13:38 UTC
