### ISSUE TITLE
[Bug]: application killed when switching from termux to termux-x11

### ISSUE THREAD

**Issue by natebragg** [termux/termux-x11#699] opened 2024-08-13 18:18 UTC
### Problem description

I run `TERMUX_X11_DEBUG=1  termux-x11 :0 -xstartup xclock` in termux.  I then switch apps to termux-x11, which flashes and then goes back to the 'not connected' screen.

When I go back to termux and look at the log the last line is `X connection to :0 broken (explicit kill or server shutdown).`  Although I used `xclock` here, this happens for each of the various applications I tested.

I am using a Samsung SM-T820 tablet.

### What steps will reproduce the bug?

See above.

**Comment by twaik** [comment] 2024-08-13 18:27
Probably you should post the `logcat` output. Run `logcat > log.txt 2>&1` after termux-x11 stops and post here the log file. Not screenshot.

**Comment by natebragg** [comment] 2024-08-14 14:51
[log.txt](https://github.com/user-attachments/files/16614984/log.txt)

Nothing jumps out to me immediately.  I don't even see `xclock` mentioned.

**Comment by twaik** [comment] 2024-08-15 06:49
It seems like termux-x11 is killed with SYS_SECCOMP. It is pretty much weird, it should not behave this way. And I do not see any way to fix it because it is caused by your firmware, probably after system update.

**Comment by natebragg** [comment] 2024-08-15 13:13
Oh, and when exiting from split screen, it now works fine.  Switching between the two apps does not cause xclock to be killed.  So this is clearly an issue with initially launching the app.  Perhaps there's a good way to catch this in action via app-specific logging?

**Comment by natebragg** [comment] 2024-08-16 22:32
Another update---I tried to see if `strace termux-x11` could give any insight, and interestingly when I run it and then quickly switch to the server, `strace` slows things down enough that it worked sometimes, and crashed others.  If I run this without changing, however, it crashes after switching.  As far as I can tell, modulo memory addresses and such, the `strace` logs are similar.

**Comment by peasoft** [comment] 2024-10-03 02:03
Reproduced on an OPPO device with Android 10.

1. Open Termux X11
2. Switch to Termux and run `termux-x11`
3. Switch to Termux X11
4. Connection lost, `termux-x11` was killed

However:

1. Open Termux and run `termux-x11`
2. Open Termux X11
3. Switch to Termux
4. Everything is fine

**Comment by twaik** [comment] 2024-11-26 20:17
@natebragg Can you please try 
```
clang -o libsetgid.so -shared -x c - <<< "void setgid(void){}"
```
And then
```
LD_PRELOAD=libsetgid.so termux-x11 :0 -xstartup xclock
```
?

**Comment by natebragg** [comment] 2024-11-28 14:48
@twaik This does not crash!  I love this, quite ingenious.  The only downside is that `xclock` does not display, but that is a separate issue.  Unfortunately, if I run `xterm` instead, it still crashes with the same error as before. `gvim` is also killed.

**Comment by twaik** [comment] 2024-11-28 15:00
Probably you should do `clang -o libsetgid.so -shared -x c - <<< "int setgid(void){ return 0; }"` and add `LD_PRELOAD=libsetgid.so` to the `~/.bashrc`. There are not a chance it is not a bug in your firmware.

**Comment by twaik** [comment] 2024-12-10 20:21
I am closing this because it seems to be firmware-related quirk.

**Closed by twaik** 2024-12-10 20:21 UTC

**Comment by Matthi-exe** [comment] 2025-08-16 16:02
I personally had the same problem but it's actually easy to solve. All u have to do is to use the  "termux:widget" or "termux:floating" aps to keep the session running while you're using X11.
