### ISSUE TITLE
Modifier keys from virtual keyboards no longer detected in X11

### ISSUE THREAD

**Issue by Rhys-T** [termux/termux-x11#272] opened 2023-03-09 22:24 UTC
The <kbd>Control</kbd>, <kbd>Alt</kbd>, and <kbd>Windows</kbd>[^win] keys in Hacker's Keyboard no longer seem to work in Termux:X11. I have also tried the <kbd>Control</kbd> keys in both the Samsung Keyboard and FlorisBoard, and they don't seem to be recognized either. I believe this may be the same problem mentioned in https://github.com/termux/termux-x11/issues/256#issuecomment-1455358773.

[^win]: Also known as <kbd>Meta</kbd> to Android, or <kbd>Super</kbd> to X11.

I understand that [the keys by themselves don't cause HK to send any events, and thus can't be detected separately](https://github.com/termux/termux-x11/issues/256#issuecomment-1456254235). However, previously if I pressed a normal key while one was down, X11 would at least get a key-down event for the modifier just before the main key, and a key-up for the modifier immediately afterwards, so that it knew those keys were active. This no longer appears to be happening for anything except the <kbd>Shift</kbd> key. `xev -event keyboard` no longer shows those events. `i3` doesn't detect e.g. the <kbd>Win</kbd>-<kbd>Shift</kbd>-<kbd>Q</kbd> sequence to close a window. Firefox doesn't recognize <kbd>Ctrl</kbd>-<kbd>C</kbd> and <kbd>Ctrl</kbd>-<kbd>V</kbd> to copy/paste, and just types those letters.

These modifier keys were working in build \#14 of twaik's fork (now gone as far as I can tell). The problem started after I ran into #256 and grabbed the latest successful build ([\#325](https://github.com/termux/termux-x11/actions/runs/4369839484)) from this repository.

**Edit**: Forgot to mention - the <kbd>Ctrl</kbd> and <kbd>Alt</kbd> keys in the extra-keys bar work fine.

**Comment by twaik** [comment] 2023-03-09 23:31
I'll check what I can do. It can brake some other functionality.

**Comment by Rhys-T** [comment] 2023-03-10 01:27
Okay. Is there any way I can add a <kbd>Super</kbd> key to the extra-keys bar for now? I didn't see anything in the docs about it, or any support for it near the code that handles <kbd>Ctrl</kbd>/<kbd>Alt</kbd>/<kbd>Shift</kbd> extra keys, but I'm not that familiar with the codebase, and wanted to make sure I wasn't missing something.

**Comment by emacs-newer** [comment] 2023-03-10 04:46
same to me using unexpected keyboard.

**Comment by ivam3** [comment] 2023-04-05 10:16
A same issue here

**Comment by ivam3** [comment] 2023-04-13 01:06
The issue is still opened ... is there any solution about it (extra keys[ctrl-alt-shifh] dont respond)??

**Comment by ivam3** [comment] 2023-04-18 05:46
We still are waiting for an update to fix it ... ... ...

**Comment by Rhys-T** [comment] 2023-05-02 17:05
It turns out Hacker's Keyboard _does_ have the ability to send events/keycodes for Ctrl, Alt, and Meta[^notshift] - it's just off by default. However, turning that on seems to have no effect on Termux:X11, whether I select the 'left' or 'right' versions of the keycodes - according to `xev`, the events for those keys still never appear, and the `flags` for any 'normal' keys pressed while holding the modifiers are still `0`. (I've confirmed that the events _are_ being sent by HK with those settings on, using `xev` under TigerVNC.) Not sure if this info helps at all, but I ran across those settings and figured they were worth testing.

[^notshift]: Not Shift though, for whatever reason. But Shift is already working in Termux:X11, so…

**Comment by ivam3** [comment] 2023-05-07 03:58
In my case I'm using a hardware keyboard and it worked fine in termux-x11 older versión but in all available releases doesn't work and I can't use a simple ctrl+c

**Comment by ivam3** [comment] 2023-05-07 04:01
> Verificaré que puedo hacer. Puede frenar alguna otra funcionalidad.

Do you have any solution man? ... or any idea what I can do to fix it ?

**Comment by Rhys-T** [comment] 2023-05-11 18:29
Just tried the `x11-client-experimental` branch, and it seems to be having the same issue there.

Upon closer examination, it's not _entirely_ ignoring the modifier keys (in either branch) - if I press e.g. <kbd>Alt</kbd>-<kbd>C</kbd>, it doesn't show any modifiers pressed, but the keysym _does_ change to one for 'ç' (`keysym 0xe7, ccedilla`). It looks like Termux:X11 is trying to pass through the characters that Android generates for a given key sequence, rather than the keys themselves, [similar to AVNC](https://github.com/gujjwal00/avnc/issues/163#issuecomment-1523310470).

As a temporary workaround, would it be possible to add support for the <kbd>Meta</kbd>/<kbd>Super</kbd> key to the extra-keys bar, so we can at least have a full set of modifier keys there?

**Comment by MTSYuki** [comment] 2023-05-22 20:00
After I tried a few keyboards (that have CTRl, ALT, etc...) , the only one that works with termux-x11 is [this](https://play.google.com/store/apps/details?id=com.jbak2.JbakKeyboard&hl=en_US) (Although I'd recommend install from the website, as is more up to date).
But, it need to tweak around a bit to make like a PC. I'm just make my own layout using [this](https://play.google.com/store/apps/details?id=com.jbak2.layout&hl=en_US) as tool.
I don't think anyone will have the patience to make thier own. But at least, the default English layout have hidden "Terminal keys" that you have to use from.

**Comment by twaik** [comment] 2023-05-25 05:19
Fixed by https://github.com/termux/termux-x11/commit/ee2224e474ce0c184de7a2c9c454c658f8afe249.

**Closed by twaik** 2023-05-25 05:19 UTC
