### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: library "libXlorie.so" not found

### ISSUE THREAD

**Issue by nightshade427** [termux/termux-x11#438] opened 2023-08-26 22:23 UTC
Been using termix-x11 successfully for long time, today though I get this error. Running latest android s22+ android 13 august update, latest termux pkg upgrade, latest termix-x11 companion deb. 

I get the following error:

```
java.lang.UnsatisfiedLinkError: dlopen failed: library "libXlorie.so" not found         at java.lang.Runtime.loadLibrary0(Runtime.java:1077)                            at java.lang.Runtime.loadLibrary0(Runtime.java:998)                             at java.lang.System.loadLibrary(System.java:1661)                               at com.termux.x11.CmdEntryPoint.<clinit>(CmdEntryPoint.java:169)                at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)                                      at com.termux.x11.Loader.main(Loader.java:111)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:411)
java.lang.RuntimeException: Only one Looper may be created per thread
        at android.os.Looper.prepare(Looper.java:123)
        at android.os.Looper.prepareMainLooper(Looper.java:137)
        at com.termux.x11.CmdEntryPoint.<clinit>(CmdEntryPoint.java:178)
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at com.termux.x11.Loader.main(Loader.java:111)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:411)
java.lang.UnsatisfiedLinkError: No implementation found for boolean com.termux.x11.CmdEntryPoint.start(java.lang.String[]) (tried Java_com_termux_x11_CmdEntryPoint_start and Java_com_termux_x11_CmdEntryPoint_start___3Ljava_lang_String_2)
        at com.termux.x11.CmdEntryPoint.start(Native Method)
        at com.termux.x11.CmdEntryPoint.<init>(CmdEntryPoint.java:55)
        at com.termux.x11.CmdEntryPoint.lambda$main$0(CmdEntryPoint.java:43)
        at com.termux.x11.CmdEntryPoint$$ExternalSyntheticLambda0.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at com.termux.x11.CmdEntryPoint.main(CmdEntryPoint.java:44)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.termux.x11.Loader.main(Loader.java:113)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:411)
```

**Comment by nightshade427** [comment] 2023-08-27 00:24
issue seems to be with this change from using ```System.loadLibrary("Xlorie");```

in this commit
https://github.com/termux/termux-x11/commit/d9cfc6e4d0fbe5baae68c044d639a939433ab607#diff-7d94e5587a92dea1cea02f849c54107d6267402005515e89c9fa78d46d0ac0e9R181

**Comment by nightshade427** [comment] 2023-08-27 00:26
rolled back to companion package in and it works https://github.com/termux/termux-x11/actions/runs/5685628894

**Comment by nightshade427** [comment] 2023-08-27 00:26
can we switch back to using the system loading?

**Comment by twaik** [comment] 2023-08-27 03:32
Duplicate of #436

**Closed by twaik** 2023-08-27 03:32 UTC

**Comment by nightshade427** [comment] 2023-08-27 03:36
I used ```pkg in x11-repo && pkg in termux-x11-nightly```

**Comment by twaik** [comment] 2023-08-27 03:57
Ok, try that again in a few hours. The package in repos was updated.

**Comment by nightshade427** [comment] 2023-08-27 16:43
all working now with lateat update today, thanks
