### ISSUE TITLE
App window title bar

### ISSUE THREAD

**Issue by testman42** [termux/termux-x11#581] opened 2024-03-15 09:18 UTC
On LineageOS 21 (Android 14), the app window has a titlebar on the external display or in the freeform mode.
So while the "Fullscreen on device display" option in the termux-x11 settings does work fine, it makes it so that small part of the top of the X11 desktop gets hidden under the titlebar.
I would take a screenshot if I knew how to take screenshots of the external display.
Anyway, i went to check if there are any applications that manage to remove the titlebar on themsleves when in fullscreen.
NewPipe does not manage to remove it, but it does make it transparent, so that the video content under it is still visible.
VLC seems to remove it properly, making the playing video take up whole available screen.

**Comment by twaik** [comment] 2024-03-19 07:30
Unfortunately I can not identify the peace of code in VLC which makes this possible.

**Comment by twaik** [comment] 2024-03-24 14:05
Can you please record your screen to show what exactly you are talking about?

**Comment by twaik** [comment] 2024-03-25 13:43
@testman42 Unfortunately I can not find any AVD or Virtualbox images of LineageOS 21. You should help here.

**Comment by testman42** [comment] 2024-03-25 15:39
This is how things look for me on LOS21, FP4, USB dock, HDMI monitor.
Firefox (Fenix):
![](https://obzorje.kompot.si/apps/files_sharing/publicpreview/Yg4FqxaP7mrBJ6T?file=/2024-03-25-16-11-54-277.jpg&fileId=9129257&x=1366&y=768&a=true)
notice the black title bar at the top
NewPipe:
![](https://obzorje.kompot.si/apps/files_sharing/publicpreview/Yg4FqxaP7mrBJ6T?file=/2024-03-25-16-23-12-693.jpg&fileId=9129241&x=1366&y=768&a=true)
still visible buttons, but video takes up the whole screen
VLC:
![](https://obzorje.kompot.si/apps/files_sharing/publicpreview/Yg4FqxaP7mrBJ6T?file=/2024-03-25-16-27-44-641.jpg&fileId=9129266&x=1366&y=768&a=true)
same video, but no titlebar
however, I suspect that this is some casting wizardry, as here the video does not play inside the application window, but apparently outside of it. As application window shows can be opened on the phone screen and it shows some "casting" icon and playback controls
![](https://obzorje.kompot.si/apps/files_sharing/publicpreview/Yg4FqxaP7mrBJ6T?file=/2024-03-25-16-27-57-413.jpg&fileId=9129244&x=1366&y=768&a=true)

**Comment by testman42** [comment] 2024-03-25 15:57
Why is this important to me?
because I have to use termux-x11 in a "windowed" mode
![](https://obzorje.kompot.si/apps/files_sharing/publicpreview/Yg4FqxaP7mrBJ6T?file=/2024-03-25-16-51-21-664.jpg&fileId=9129293&x=1366&y=768&a=true)
if the "Fullscreen on device display" is enabled, then the tabs in desktop Firefox get hidden under Android titlebar.
![](https://obzorje.kompot.si/apps/files_sharing/publicpreview/Yg4FqxaP7mrBJ6T?file=/2024-03-25-16-52-20-593.jpg&fileId=9129300&x=1366&y=768&a=true)

**Comment by twaik** [comment] 2024-03-25 16:53
Probably you should try to find some other opensource application that can do the fullscreen magic. Otherwise I will not be able to help you an will close the issue.

**Comment by twaik** [comment] 2024-04-01 15:58
I am considering this as device or custom firmware quirk since other programs which are normally can use fullscreen feature fail to use fullscreen on your device.
You should file a bug to LineageOS authors or XDA thread where you got this firmware. 
One more reason to close the issue is the lack of activity.

**Closed by twaik** 2024-04-01 15:58 UTC

**Comment by twaik** [comment] 2026-07-28 18:27
Did you try using 
```
am start -S -a android.intent.action.MAIN -c android.intent.category.SECONDARY_HOME -n com.termux.x11/.MainActivity
```

?
