### ISSUE TITLE
Extra Keys always on bottom screen

### ISSUE THREAD

**Issue by Yonle** [termux/termux-x11#58] opened 2021-11-01 15:14 UTC
As the title said, The extra keys always on bottom side, not hide it's man by itself. 

Unlike older version, Extra keys only shows up when soft keyboard is there.

**Comment by Yonle** [comment] 2021-11-02 15:10
No.

**Comment by twaik** [comment] 2021-11-02 16:56
Where exactly did you get an installation package?

**Comment by Yonle** [comment] 2021-11-02 17:08
This artifacts: https://github.com/termux/termux-x11/actions/runs/1331295113

**Comment by twaik** [comment] 2021-11-02 19:48
Ok, I'll check what is happening here. Thanks for your report.

**Comment by WMCB-Tech** [comment] 2021-12-06 05:29
The [ekeys](https://github.com/termux/termux-x11/pull/19) branch should solve it however it's not complete rather

**Comment by twaik** [comment] 2023-02-02 00:26
Can you please check if it still relevant?

**Comment by Yonle** [comment] 2023-02-04 09:29
Sorry. I am no longer using Termux:X11.

**Comment by twaik** [comment] 2023-02-04 09:58
@stopka-html ?

**Comment by stopka-html** [comment] 2023-02-04 15:36
> @stopka-html ?

Yep

**Comment by stopka-html** [comment] 2023-02-04 15:38
> @stopka-html ?

I can't say about it because i just use full screen mode

**Comment by twaik** [comment] 2023-02-04 18:14
Can you please disable fullscreen mode for 5 minutes and check?

**Comment by twaik** [comment] 2023-02-09 12:18
@stopka-html ?

**Comment by stopka-html** [comment] 2023-02-09 16:24
> @stopka-html ?

it keeps showing up

**Comment by stopka-html** [comment] 2023-02-09 16:24
> @stopka-html ?

it keeps showing up

**Comment by twaik** [comment] 2023-03-01 22:44
Can you please test latest build [here](https://github.com/twaik/termux-x11/actions)? You can try triple finger swipe down to toggle extra keys.

**Comment by Rhys-T** [comment] 2023-03-02 00:00
Just tried [build #12](https://github.com/twaik/termux-x11/actions/runs/4308842123) from your repository. I'm having the same issue (extra keys bar shows up even though it's unchecked in preferences), but swiping down with three fingers does work to show/hide it.

**Comment by twaik** [comment] 2023-03-02 00:10
> extra keys bar shows up even though it's unchecked in preferences

Yeah, definitely my fault. I forgot to test it. Will be done.

**Comment by twaik** [comment] 2023-03-02 00:34
New build with fix for this will be available in 4 minutes.

**Comment by Rhys-T** [comment] 2023-03-02 00:59
[Your build #14](https://github.com/twaik/termux-x11/actions/runs/4309342747) seems to have fixed that - the extra keys are gone now. I noticed that I can't swipe to toggle them unless the main switch for them is turned on in the preferences. It's not a problem for me (I don't really use the extra keys, since I'm using Hacker's Keyboard), but I could see it being useful to have a mode where they start hidden, but can be toggled on later by swiping.

(Also, I brought up the preferences using the shortcut while Termux:X11 and Xwayland were both running, backed out of them when I was done, and when I tried to go back to the main Termux:X11 screen, it just took me to a white screen with the logo. I couldn't find any way back to X11, and ended up having to quit everything and start over. Did I do something wrong? If not, should I open an issue for this?)

**Comment by twaik** [comment] 2023-03-02 01:03
Maybe I did something wrong, but now I can not reproduce this. Can you please post a video showing this? 
And you do not need to quit everything and start over. You can simply kill Android app and start it again. Main feature of these builds is connecting to existing session.

**Comment by Rhys-T** [comment] 2023-03-02 01:23
Here's the video. It was actually slightly different this time: Before, once I got to the white screen, the Back button did nothing, but as far as I remember the Home button worked fine. This time, they _both_ did nothing, and stayed highlighted after I let go of them. (The Recent Apps button worked fine, fortunately - that's just where I trimmed the video.) Don't know if the screen recorder was interacting weirdly with Termux:X11, or what.

Force-stopping just Termux:X11 and bringing it back up did work. I didn't realize it was split like that, and was thinking that the server was running in the app itself, and would get killed with the rest of it.

https://user-images.githubusercontent.com/108157737/222305646-73e3209b-b1a8-431c-80f1-d11a9bfb1500.mp4

**Comment by twaik** [comment] 2023-03-02 01:32
It is weird. Can you please post a logcat?

**Comment by Rhys-T** [comment] 2023-03-02 02:09
…Well, I would, if I could get it to happen again. For some reason it's working fine now. Maybe I confused something earlier with all the killing/relaunching, and rebooting the tablet fixed it. Sorry for the noise. I'll let you know if it happens again and I can replicate it.

**Comment by twaik** [comment] 2023-03-02 11:15
Is a problem fixed in my fork? Can I close the issue?

**Comment by Rhys-T** [comment] 2023-03-02 14:03
I think that fork has fixed it - I'll let you know if I discover otherwise. As far as I'm concerned, this can be closed now.

**Closed** 2023-03-02 14:13 UTC
Labels: bug

**Comment by rsanjuan87** [comment] 2024-07-17 08:08
I facing this problem
Termux:X11 version: `1.03.01-033ee16-07.07.24`

**Comment by twaik** [comment] 2024-07-17 08:17
It is not the same problem. What you see is a software keyboard (also called IME). Invoke a back button.

**Comment by rsanjuan87** [comment] 2024-07-17 08:19
> It is not the same problem. What you see is a software keyboard (also called IME). Invoke a back button.

but extra keys shows below the softkey ...

**Comment by twaik** [comment] 2024-07-17 08:34
@rsanjuan87 ?

**Comment by twaik** [comment] 2024-07-17 08:37
The cursor always jumps to the centre of screen when surface is being resized. Not a bug.

**Comment by twaik** [comment] 2024-07-17 08:37
> I facing this problem

You said you have the same problem. But you have not.

**Comment by rsanjuan87** [comment] 2024-07-17 08:39
Id refer to extra keys keeps on bottom. keeping below softkey

**Comment by rsanjuan87** [comment] 2024-07-17 08:40
should open new issue?

**Comment by twaik** [comment] 2024-07-17 16:05
Can not reproduce it. Probably a device or ime quirk.
