### ISSUE TITLE
XDG-WM-Base missing

### ISSUE THREAD

**Issue by parkerlreed** [termux/termux-x11#40] opened 2021-09-29 19:31 UTC
wayland 1.19.0
xorg-xwayland 21.1.2

Arch Linux Aarch64 chroot (not proot)

Termux-X11 tmp dir is bind mounted to a folder within chroot. It finds the folder and sockets but complains about missing XDG-WM-Base protocol.

```
[root@localhost /]# Xwayland :1 > /dev/null &
[1] 15836
[root@localhost /]# glamor: No eglstream capable devices found
missing XDG-WM-Base protocol
(EE)
Fatal server error:
(EE) Couldn't add screen
(EE)

[1]+  Exit 1                  Xwayland :1 > /dev/null
```

**Comment by twaik** [comment] 2021-09-30 08:23
You should not use `Xwayland` that is present in chrooted environment. It is not patched to work with Lorie. You should create $PREFIX/tmp/.X11_unix is it is not present and then `mount --bind` it to chrooted environment's /tmp/.X11_unix. After that you can start Lorie and `Xwayland` in termux.

**Comment by twaik** [comment] 2021-09-30 08:24
Please, let me know if it worked.

**Comment by RalfWerner** [comment] 2021-09-30 08:49
> After that you can start Lorie and Xwayland in termux.

I have been working so for years without problems. When using _distros_ (`proot-distro`) is there (in your case) only to do:
`(export) DISPLAY=:1`

**Comment by parkerlreed** [comment] 2021-10-08 14:57
I see the readme updated with some new instructions so I will give that a shot when I can

Thanks.

**Comment by parkerlreed** [comment] 2021-10-10 00:04
Confused as ever... 

https://user-images.githubusercontent.com/841440/136676767-71f477bd-cc02-45f1-8495-dfd51d60bff3.mp4

**Comment by parkerlreed** [comment] 2021-10-10 00:14
Still doesn't like it but slightly new error
![Screenshot_20211009-201434_Termux](https://user-images.githubusercontent.com/841440/136676924-c1d51892-6ae0-41b5-9e9c-fdf358c48d38.png)

**Comment by Heasterian** [comment] 2021-10-16 17:00
That "No protocol specified" message looks a bit generic. Did you try to use `xhost +local:` or even `xhost +` command in Termux after starting `termux-x11` in console?

**Comment by twaik** [comment] 2021-10-16 17:22
I found out where is the root of problem. Xwayland moved from wl_shell to xdg_wm_base protocol. That means new Xwayland is not compatible with Lorie. Will be fixed with moving to wlroots. Of cource if I will succeed in porting it...

**Comment by untoreh** [comment] 2021-12-27 14:17
I can start a DE from a linuxdeploy container by mounting the X11 socket. However glxgears can't run, giving
`Error: couldn't get an RGB, Double-buffered visual.`
I assume this is because a linuxdeploy container doesn't have HW acceleration, whereas like xfce4 from termux is using proper mesa drivers?

**Comment by twaik** [comment] 2021-12-27 15:18
Termux:X11 has no acceleration support for now.

**Comment by Heasterian** [comment] 2021-12-28 07:52
> I can start a DE from a linuxdeploy container by mounting the X11 socket. However glxgears can't run, giving `Error: couldn't get an RGB, Double-buffered visual.` I assume this is because a linuxdeploy container doesn't have HW acceleration, whereas like xfce4 from termux is using proper mesa drivers?

This errors is most likely caused by version missmatch of wayland-protocols or xwayland package between chroot and Termux. You need to use same version on both of them.

**Comment by Azkali** [comment] 2021-12-28 14:56
Made a script which just compiles instructions took from here :

It is meant for native termux, I will share later how I got acceleration working inside a gentoo prefix, but here you go for now :
https://gitlab.com/Azkali/adreno_termux

**Comment by iamSlightlyWind** [comment] 2022-02-08 19:51
> Made a script which just compiles instructions and patches took here: https://gxmersam.blogspot.com/p/getting-hardware-acceleration-on-termux.html
> 
> It is meant for native termux, I will share later how I got acceleration working inside a gentoo prefix (which should work in proot and chroot as well), but here you go for now : https://gitlab.com/Azkali/adreno_termux
> 
> Edit: Also bootstraping a gentoo prefix for non-root users with different profiles for different usage. And more to come on my gitlab profile.

@Azkali Hi, I'm trying to follow your instructions, but I'm having a problem finding `~/dir/wayland-protocols/autogen.sh` when compiling wayland protocols. I can't find the `autogen.sh` on [their repository](https://github.com/wayland-project/wayland-protocols) either. Also, it seems that you already compiled Xwayland in compiling xorgproto part, not that it makes a difference. Can you tell me where can I find the `autogen.sh` in
```
cd ~/dir/wayland-protocols
./autogen.sh --prefix $PREFIX```

Thanks!

**Comment by parkerlreed** [comment] 2022-02-08 22:03
Looks like they changed over to meson for the build system. May be able to simply see what they suggest for building and modify the script accordingly.

**Comment by iamSlightlyWind** [comment] 2022-02-08 22:30
I _**think**_ I was able to correctly built wayland-protocols, however their guide also mentions files that previously don't exist: `~/instructions/patches/mesa/*.patch` , `~/instructions/patches/epoxy/*.patch` and `~/instructions/patches/xorg/*.patch`. I have no idea how many `.patch`s there were, or where to get them. Ignoring the patches leads to build errors which again I have no idea if they were caused by missing patches, or missing dependencies (`nm` of `binutils` was also needed in the required packages, but not present on the guide).

**Comment by twaik** [comment] 2022-02-08 22:35
@iamSlightlyWind that is from suhan-paradkar's tewmux-disabled.

<details>
  <summary>Screenshot</summary>

  
![Screenshot_20220209-003259_Chrome](https://user-images.githubusercontent.com/9674930/153086978-5bc5b287-8980-4731-b50e-7183b9a0d76a.jpg)

  
</details>

**Comment by twaik** [comment] 2022-02-09 14:54
@iamSlightlyWind  Can you please make one more video with VLC using different renderers (GLES, GL, xcb, xrender)?

**Comment by DLC01** [comment] 2022-02-09 15:00
> I _**think**_ I was able to correctly built wayland-protocols, however their guide also mentions files that previously don't exist: `~/instructions/patches/mesa/*.patch` , `~/instructions/patches/epoxy/*.patch` and `~/instructions/patches/xorg/*.patch`. I have no idea how many `.patch`s there were, or where to get them. Ignoring the patches leads to build errors which again I have no idea if they were caused by missing patches, or missing dependencies (`nm` of `binutils` was also needed in the required packages, but not present on the guide).

an new version of the instructions and patches were released quite [recently]( https://github.com/suhan-paradkar/tewmux-disabled/releases/tag/mesa-hw-v2) which should adress most of the build issues

**Comment by iamSlightlyWind** [comment] 2022-02-09 21:12
> @iamSlightlyWind Can you please make one more video with VLC using different renderers (GLES, GL, xcb, xrender)?

I don't actually understand what specific things you want me to try. My understanding is that you want me to try with VLC installed in a proot. Although, I was able to try `glmark2-es` with results: 
```
=======================================================
    glmark2 2021.12
=======================================================
    OpenGL Information
    GL_VENDOR:     Collabora Ltd
    GL_RENDERER:   zink (Adreno (TM) 650)
    GL_VERSION:    OpenGL ES 3.1 Mesa 21.2.0-devel (git-b897012054)
=======================================================
[jellyfish] <default>:WARNING: linker: Warning: "/vendor/lib64/libllvm-qgl.so" unused DT entry: unknown processor-specific (type 0x70000001 arg 0x0) (ignoring)
 FPS: 57 FrameTime: 17.544 ms
[refract] <default>: FPS: 52 FrameTime: 19.231 ms
[terrain] <default>: FPS: 43 FrameTime: 23.256 ms
[desktop] <default>: FPS: 34 FrameTime: 29.412 ms
=======================================================
                                  glmark2 Score: 46
=======================================================
```

comparing to glmark2(mesa?), removed warnings:
```
=======================================================
    glmark2 2021.12
=======================================================
    OpenGL Information
    GL_VENDOR:     Collabora Ltd
    GL_RENDERER:   zink (Adreno (TM) 650)
    GL_VERSION:    2.1 Mesa 21.2.0-devel (git-b897012054)
=======================================================
[jellyfish] <default>:WARNING: linker: Warning: "/vendor/lib64/libllvm-qgl.so" unused DT entry: unknown processor-specific (type 0x70000001 arg 0x0) (ignoring)
 FPS: 111 FrameTime: 9.009 ms
[refract] <default>: FPS: 63 FrameTime: 15.873 ms
[terrain] <default>: FPS: 54 FrameTime: 18.519 ms
[desktop] <default>: FPS: 89 FrameTime: 11.236 ms
=======================================================
                                  glmark2 Score: 79
=======================================================
```
Though, this may not be what you are looking for since the renderer still said it's zink. Sorry, I don't have any experience beforehand as to how to do all this but I prob can follow instructions. ATM I'm just trying to get termux:x11 to work in chroot according to #45 with hopefully some sort of hardware acceleration based on this script/method since xsdl server is pissing me off.

**Closed** 2023-02-01 15:18 UTC
Labels: bug

**Comment by parkerlreed** [comment] 2023-02-01 15:29
Holy crap. Thank you! Excited to try this again.

**Comment by twaik** [comment] 2023-02-01 15:32
In video in this [post](https://github.com/termux/termux-x11/issues/40#issuecomment-939379134) you started `termux-x11` but did not specify display number. You should do it like this: `termux-x11 :1 -shm -one` .
