### ISSUE TITLE
gnome-session-binary doesn't work

### ISSUE THREAD

**Issue by Cavig01** [termux/termux-x11#370] opened 2023-07-08 12:11 UTC
I was using Manjaro from proot-distro, and the following outputs were received everytime when I tried to start Gnome with Termux:X11 :
```
[root@localhost ~]# termux-x11 :1 -xstartup "dbus-launch --exit-with-session gnome-session"
java.io.FileNotFoundException: /data/system/theme_config/theme_compatibility.xml: open failed: ENOENT (No such file or directory)
        at libcore.io.IoBridge.open(IoBridge.java:575)
        at java.io.FileInputStream.<init>(FileInputStream.java:160)
        at java.io.FileInputStream.<init>(FileInputStream.java:115)
        at java.io.FileReader.<init>(FileReader.java:58)
        at miui.content.res.ThemeCompatibilityLoader.getVersion(ThemeCompatibilityLoader.java:108)
        at miui.content.res.ThemeCompatibilityLoader.getConfigDocumentTree(ThemeCompatibilityLoader.java:126)
        at miui.content.res.ThemeCompatibilityLoader.loadConfig(ThemeCompatibilityLoader.java:59)
        at miui.content.res.ThemeCompatibility.<clinit>(ThemeCompatibility.java:31)
        at miui.content.res.ThemeCompatibility.isThemeEnabled(ThemeCompatibility.java:111)
        at android.content.res.MiuiResourcesImpl.<clinit>(MiuiResourcesImpl.java:41)
        at android.content.res.MiuiResources.<init>(MiuiResources.java:58)
        at android.content.res.IMiuiResourceImpl.createResources(IMiuiResourceImpl.java:13)
        at android.content.res.ThemeManagerStub.createMiuiResources(ThemeManagerStub.java:56)
        at android.content.res.Resources.getSystem(Resources.java:235)
        at android.app.ActivityManager.isHighEndGfx(ActivityManager.java:1097)
        at android.view.ThreadedRenderer.initForSystemProcess(ThreadedRenderer.java:217)
        at android.app.ActivityThread.systemMain(ActivityThread.java:8035)
        at com.termux.x11.Loader.main(Loader.java:37)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:363)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:567)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:273)
        at libcore.io.IoBridge.open(IoBridge.java:561)
        ... 19 more
gnome-session-binary[2730]: WARNING: Failed to upload environment to systemd: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Name "org.freedesktop.systemd1" does not exist
gnome-session-binary[2730]: WARNING: Failed to reset failed state of units: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Name "org.freedesktop.systemd1" does not exist
gnome-session-binary[2730]: WARNING: Falling back to non-systemd startup procedure due to error: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Name "org.freedesktop.systemd1" does not exist
gnome-session-binary[2730]: ERROR: Failed to connect to system bus: Could not connect: No such file or directory
aborting...
2730 killed by signal 5
```
To figure out what was happening, I tried Xfce instead. **The “java.io.FileNotFoundException” was still there, but Xfce could run normally.**
Then I tried to start the “gnome-session” only. The “java.io.FileNotFoundException” was not there this time, but it still only gave me these:
```
[root@localhost ~]# gnome-session
gnome-session-binary[6467]: WARNING: Failed to upload environment to systemd: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Name "org.freedesktop.systemd1" does not exist
gnome-session-binary[6467]: WARNING: Failed to reset failed state of units: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Name "org.freedesktop.systemd1" does not exist
gnome-session-binary[6467]: WARNING: Falling back to non-systemd startup procedure due to error: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Name "org.freedesktop.systemd1" does not exist
gnome-session-binary[6467]: ERROR: Failed to connect to system bus: Could not connect: No such file or directory
aborting...
Trace/breakpoint trap
``` 
I believe the issue was caused by Gnome itself, but I don't know how to fix it. May I ask how can I deal with it?

**Comment by twaik** [comment] 2023-07-08 12:13
Duplicate of #340 . 
See https://github.com/termux/termux-x11/issues/340#issuecomment-1580624273 .

**Closed by twaik** 2023-07-08 12:13 UTC

**Comment by Cavig01** [comment] 2023-07-08 12:15
> Duplicate of #340 . See [#340 (comment)](https://github.com/termux/termux-x11/issues/340#issuecomment-1580624273) .

Thanks for replying
