### ISSUE TITLE
[Bug]: termux-x11 screen stuck in mediatek helio G95 proccesors fix this

### ISSUE THREAD

**Issue by Cloud-pc41** [termux/termux-x11#719] opened 2024-09-09 03:10 UTC
### Problem description

Termux-x11 screen got stuck in mediatek helio G95 proccesors fix it 

### What steps will reproduce the bug?

Stuck screen

**Comment by twaik** [comment] 2024-09-09 04:06
Duplicate of #516

**Closed by twaik** 2024-09-09 04:06 UTC
