### ISSUE TITLE
incorrect cursor position in the latest apk

### ISSUE THREAD

**Issue by kde-yyds** [termux/termux-x11#218] opened 2023-02-06 07:14 UTC
https://user-images.githubusercontent.com/106876912/216907125-5b68e9a4-2551-4402-ab00-07a8e71f2eda.mp4

the cursor position in termux-x11 is always higher than the touch point

**Comment by a858438680** [comment] 2023-02-13 09:33
Same issue, the latest 3 builds (#8bb8be1, #daa3485, #96b35a4) all have the same problem.
At the top, the error is zero, at the bottom the error is basically the height of the notification bar.

**Comment by twaik** [comment] 2023-02-13 09:52
I am already on it.

**Comment by a858438680** [comment] 2023-02-13 10:20
> I am already on it.

thanks very much

**Comment by Dendi777** [comment] 2023-02-14 06:02
Most likely, as I told you before, perhaps the problem with the cursor arises because of the screen resolution, you clearly need to add a resolution selection function like in vnc!

**Comment by twaik** [comment] 2023-02-14 06:11
I am aware of a problem with a cursor and already on it. Cursor positioning problem is not related to screen resolution.
And I already work on screen resolution function. https://github.com/termux/termux-x11/issues/89#issuecomment-1412535954 . It will be implemented without being reminded.

**Comment by twaik** [comment] 2023-02-17 18:07
Please, confirm if it happens on latest build or not. Thank you.

**Comment by a858438680** [comment] 2023-02-17 18:18
> Please, confirm if it happens on latest build or not. Thank you.

I've tested the build #260 (#540dcbe). This problem have been solved in my Xiaomi 13.

**Comment by twaik** [comment] 2023-02-17 18:23
@kde-yyds ?

**Comment by Dendi777** [comment] 2023-02-18 06:14
I tried the last build and yes, the cursor works well, everything is as it should, but now it has become very difficult to launch the application, then it crashes and does not turn on at all, but if it does turn on, it works stably, sort of!

**Comment by Dendi777** [comment] 2023-02-18 06:16
By the way, when I start, I see a large log in which there are exceptions, they clearly hint at an error!

**Comment by Dendi777** [comment] 2023-02-18 06:20
These are two suspicious messages:
exception java.io .FileNotFoundException: /data/system/theme_config/theme_compatibility.xml : failed to open: ENOENT (there is no such file or directory)
Caused by: android.system.ErrnoException: failed to open: ENOENT (there is no such file or directory

**Comment by twaik** [comment] 2023-02-18 11:35
> By the way, when I start, I see a large log in which there are exceptions, they clearly hint at an error!

It should be long. These exceptions do not affect program lifecycle.

> now it has become very difficult to launch the application, then it crashes and does not turn on at all,

As I told you before it will be fixed a bit later...

@kde-yyds Can you please confirm if the bug gone and close the issue?

**Comment by Dendi777** [comment] 2023-02-18 13:10
Yes, the bug with the cursor is fixed!

**Comment by kde-yyds** [comment] 2023-02-18 13:52
> > By the way, when I start, I see a large log in which there are exceptions, they clearly hint at an error!
> 
> It should be long. These exceptions do not affect program lifecycle.
> 
> > now it has become very difficult to launch the application, then it crashes and does not turn on at all,
> 
> As I told you before it will be fixed a bit later...
> 
> @kde-yyds Can you please confirm if the bug gone and close the issue?

but i can only use touchpad input mode after upgrade
switching to direct mode has no effect. termux-x11 still input as touchpad

**Comment by twaik** [comment] 2023-02-18 13:54
> switching to direct mode has no effect.

It is weird, I thought I completely removed direct mode...

An issue was about incorrect cursor position.

**Closed** 2023-02-19 09:48 UTC
