### ISSUE TITLE
MB_Helper in X11 Server (Bug/Feature request)

### ISSUE THREAD

**Issue by RalfWerner** [termux/termux-x11#678] opened 2024-07-19 10:57 UTC
Inserting both `*_HELPER` into the EK Setup works well but unfortunately the display often disappears when the screen configuration is changed. I used x11 version **4e7763b** and took [three shots on two devices each,](https://github.com/user-attachments/assets/65a0b594-57c6-4039-abab-c7b5dace766d) which can be repeated.

- The first three are from a Moto/Lenovo phone. In the first two shots, the setup and display is with fluxbox + aterm XClients but without a stylus. In the third, with split screen **without** display. The same effect can also be achieved by switching on a fixed on-screen KB or rotation to landscape. The last x11 version that allowed 'STYLUS_HELPER' on this device was **1e7857c.** There is also a [video](https://github.com/RalfWerner/integrated-process/blob/master/script.md#mb_helper-in-x11-server) for the device, in which EK problems can be seen.
- The second three shots are from a Samsung Pad with Pop-View. Setup as before and display with both `*_HELPER`. In shots 2+3 both menus disappear due to on-screen KB and PopView reduction.

In order to be able to use the menus, they must appear on the screen. Once you understand the algorithm, you can use a workaround to move the menus so that they remain visible after changing the screen configuration. You could `*_HELPER` also consider as two pre/post-MB selections. In that case, there would be no need to reduce the menus to **stylus** and **trackpad.**

**Comment by RalfWerner** [comment] 2024-08-21 06:41
As the examples show above, there are cases in which the X11-EK-line is missing. The problem is always there with PopView.

Here is an [example](https://github.com/user-attachments/assets/bb7da9e7-1bd9-4e96-8898-af9473c3fc86) with TeamViewer on Win-PC without touchscreen, with a pad that shows the X11 with **aterm** and **fluxbox** and in PopView Termux-App. Both apps with 1-line EK and a joint OS-KB (Hackers). The BT mouse pointer and the Stylus are marked green.
In addition, the PC pointer can be seen on the screen. In both terminals I tried the `[][]` input via PC keyboard and OS-KB. Unfortunately, this was only successful in Termux-App.
The BT mouse pointer can only be used within X11 (not EK/KB/Termux) but with the PC mouse. This, fingers and pen can be used anywhere on the screen and are synchronized with click/touch.
EK-Touch (Cursor Up = Last Command) performs the action in the _associated_ app. 

I then exchanged the two apps (X11 in PopView). Then the **X11-EK line is missing** and I changed the OS-KB to floating Samsung. Also made a [shot of it](https://github.com/user-attachments/assets/e7414eb1-68b2-46fd-85ab-c3445aae6f5e). The BT mouse is also _"caught"_ here in the PopView window. Unfortunately, EK-Touch is no longer possible. If PopView is switched to Split view, the EK-Line only appears until the OS-KB is activated or fixed.

The MB1-3 of the BT mouse work, but the PC mouse does not. Multitouch only on the Pad possible. So a _Pre-MB-Selection_ (Stylus) would helpful.
Both Shots with missing **X11-EK line in green(?)!**
![image](https://github.com/user-attachments/assets/95cb3e6d-172b-42f4-830e-308704ee525a)

**Comment by twaik** [comment] 2024-11-27 11:45
Fixed by 01baf6203b927a45603791a5aef415a79bf1af87.

**Closed by twaik** 2024-11-27 11:45 UTC

**Comment by RalfWerner** [comment] 2024-11-27 15:25
Which of the problems described above should be fixed with the **PR?**
I've checked with `1.03.01-a0543e1-27.11.24` on two devices and didn't find a solution on any of them.
You didn't respond to my feature request at all.

**Comment by twaik** [comment] 2024-11-27 15:46
As far as I understand you described a problem of disappearing stylus/mouse helpers when you rotate device?
I do not know why but I can not read messages you write. I understand separate words but they do not make a sense when I read the whole sentence. Probably the problem both of use have English as second (third?) languange.

**Comment by RalfWerner** [comment] 2024-11-27 16:06
> Probably the problem both of use have English as second (third?) languange.

That may be. But I can understand you very well. There are lots of pictures and videos of the problems that you can easily understand. **Have you tried that?**

**Comment by RalfWerner** [comment] 2024-11-27 16:13
Це може бути. Але я вас дуже добре розумію. Є багато фотографій і відео про проблеми, які ви можете легко зрозуміти. **Ви пробували це?**
Better?

**Comment by twaik** [comment] 2024-11-27 16:18
The problem is not a language of words, the problem is sentence structure (probably).

**Comment by RalfWerner** [comment] 2024-11-27 16:27
I suspect that the problems are not easy to solve. The lack and disappearance of MB help and EK lines is easy to reproduce.
To structure sentences, I use the same algorithm that Google uses to translate websites.

**Comment by RalfWerner** [comment] 2024-11-27 18:25
> OS-KB? EK-Touch? post-MB? Samsung Pad? PopView?

The problem can be solved! From now on, I will be using the **on-screen-keyboard** instead of the **OS-KB**. **EK-Touch** means: touch on a key of the Extra-Key-Line. [Samsung Pad](https://github.com/user-attachments/assets/95cb3e6d-172b-42f4-830e-308704ee525a) is the device of the shot and **PopView** an Android feature (like split) inside X11 is used there. **post-MB** is part of my feature request [above](https://github.com/termux/termux-x11/issues/678#issuecomment-2301253524):
>You could *_HELPER also consider as two *pre/post-MB* selections. In that case, there would be no need to reduce the menus to stylus and trackpad.

It would also be very helpful to include the _scroll wheel_ in the ***.HELPER**. A double (pre/post) function would also not be necessary if it were covered by _one_ mouse symbol. I have tried to use Thunderbird+Firefox without a real mouse and KB. This is extremely tedious with the current MB-Helper. I prefer to use direct touch, where it would at least be a small help. REAL-VNC has the mouse wheel, but many things in X11 are missing. Shot [from above](https://github.com/termux/termux-x11/issues/678#issue-2418624089) again:
![image](https://github.com/user-attachments/assets/65a0b594-57c6-4039-abab-c7b5dace766d)
If it helps you, I can write an XClient that does this as an example (but it takes some time).

**Comment by twaik** [comment] 2024-11-27 18:28
> Samsung Pad

Usually it is called tablet...

> PopView

It is called Windowed mode or Freeform mode.

**Comment by RalfWerner** [comment] 2024-11-27 19:40
Samsung calls the device **SM-P610** (`getprop ro.product.model` ), where **SM** means _Samsung_ and **P** for _Pad_. If you understand me better, I can also say _tablet_. When I set the language to English, Android shows _pop-up view_ and in German: _Pop-Up-Ansicht_. Which of your two terms **do you prefer?** I would use that.

It would be more important that the _"the keys of the Extra-Key-Lines"_ (**EK**) occures and the BT-mouse pointer inside can also be moved out of the window, without having to use the stylus or fingers. Or in Split view the MOUSE_HELPER is hidden behind EK and cannot be moved or STYLUS_HELPER does not appear at all by using the popup of first **EK**
