### ISSUE TITLE
[feature request] option to factor in the height of extra keys bar into display dimension calculation

### ISSUE THREAD

**Issue by knyipab** [termux/termux-x11#605] opened 2024-04-20 08:35 UTC
The extra keys bar is currently shown on top of the display. The bar could indeed block what can be seen at the bottom of display, such as when browsing websites in a maximized browser window. It could cause inconvenience for users who want to have the bar always on, or he/she would need to hide the bar every time to see the bottom of display and then toggle the bar again. 

Therefore, it would be really great to have an option to make the app to recalculate display dimension so not to overlap with the extra keys bar whenever the bar is toggled. Thank you.

**Comment by twaik** [comment] 2024-04-21 19:01
The extra key bar was designed to be toggled on or off as needed. Intentionally. For convenient switching, you can use two gestures: a three-finger swipe or the "volume down" button (activated in the settings).

Recalculating size of EK bar and screen surface was used in older versions but it was removed because it caused flickering of screen and there is no fix for this. It will not be back again.

**Comment by RalfWerner** [comment] 2024-04-22 06:23
@knyipab The same function is also possible in the Termux app. There the **EK** with `LogTap` is toggled in the drawer - mostly. The **EK** is displayed there above the On-Screen KB. The Termux prompt is displayed above the **EK**. So is never covered.
In version `1.02.04` of Termux-x11, the same behavior has been implemented and some other functions have also been lost in `1.03.00`. However, there are also good extensions in the latest artifact. For me, the advantages of `1.02.04` predominate on _pure phones_ without additional input devices.

**Comment by knyipab** [comment] 2024-04-30 07:02
Similar to #607. Do you mind me putting this feature in a sub-page called "unstable features"?

Still, this option can be useful. Even with three-finger gesture, using the arrow buttons the navigate the terminal at the bottom of VS Code is a pain. I am happy to make a pull request make available an option under "unstable features".

**Comment by RalfWerner** [comment] 2024-04-30 08:38
I would like that very well, how I wrote in my deleted commit above.

**Comment by knyipab** [comment] 2024-05-09 18:14
Inspired by RealVNC viewer, an option for opacity of EK bar through `.setAlpha()` can be a good alternative to PR #618 , at least solving the pain point of using vs code terminal. I could implement, subject to your view.

**Comment by twaik** [comment] 2024-05-09 18:22
Probably it is a nice idea.

**Comment by twaik** [comment] 2024-05-16 07:15
Closed by #618

**Closed** 2024-05-16 07:15 UTC
