### ISSUE TITLE
[Bug]: Stylus pressure is not usable

### ISSUE THREAD

**Issue by TudbuT** [termux/termux-x11#634] opened 2024-05-15 09:14 UTC
### Problem description

Related: #315 

It seems like pressure/tilt is not working for me, despite #315 being closed as completed, which is supposed to have pressure as per issue description. GIMP sees an input device with pressure + tilt, but does not receive any events from it -> I can't use it.

My device is a Samsung Galaxy Tab S8 Ultra running [uname -a] ˋLinux localhost 5.10.168-android12-9-27940245-abX900XXS6CXB4 #1 SMP PREEMPT Mon Feb 19 06:14:03 UTC 2024 aarch64 Androidˋ.

Screenshot of the input device picker:
![SmartSelect_20240515_110504_TermuxX11](https://github.com/termux/termux-x11/assets/48156391/d5a039b6-1aca-4668-b99a-01af090bd940)

I am running gimp in archlinux-arm (the gimp provided by termux doesn't even see the input device).

### What steps will reproduce the bug?

1. Install a proot archlinux-arm on termux: https://github.com/TermuxArch/TermuxArch
2. Install xf86-input-libinput, xf86-input-evdev, and gimp
3. Open gimp
4. No pressure detection is present
5. Go to Edit > Input Devices
6. Find the one with Pressure and Tilt
7. Select screen mode on it (and no others) to make it the exclusive input device
8. No drawing is possible

### What is the expected behavior?

I should be able to use the pressure sensitive stylus for drawing in GIMP.

**Comment by twaik** [comment] 2024-05-15 09:36
Currently real stylus support is not implemented. Termux:X11 can send only transform Android stylus events to X11 mouse events.

**Comment by twaik** [comment] 2024-05-15 09:59
It seems like I found something that can help us.

**Comment by twaik** [comment] 2024-05-15 10:01
Are you using old version? I've got rid of absolute mouse 9 commits ago.

**Comment by night-nl** [comment] 2024-05-16 10:00
> Are you using old version? I've got rid of absolute mouse 9 commits ago.

Is that meaning stylus is working properly responsing to pressure?

**Comment by twaik** [comment] 2024-05-16 10:02
No. That means I've got rid of absolute mouse 9 commits ago.

**Comment by twaik** [comment] 2024-05-16 17:39
I can not reproduce it on termux's gimp on the latest artifact. 
![image](https://github.com/termux/termux-x11/assets/9674930/468b94fc-4ec2-4e2c-a95d-776e1db88625)
Devices other than core pointer are not even enumerated.

**Comment by TudbuT** [comment] 2024-05-17 14:54
> Are you using old version? I've got rid of absolute mouse 9 commits ago.

Probably. I haven't updated in a bit - will do now.

**Comment by TudbuT** [comment] 2024-05-17 15:09
New version is installed. Absolute mouse is gone as expected. 

> I can not reproduce it on termux's gimp on the latest artifact.
As I mentioned in the issue description:
> I am running gimp in archlinux-arm (**the gimp provided by termux doesn't even see the input device**).

Your termux gimp looks exactly like mine. Only the proot distro's gimp sees the individual devices. 

Here's a comparison of what i see on each now:
![SmartSelect_20240517_170655_TermuxX11](https://github.com/termux/termux-x11/assets/48156391/6b65d386-c00d-4f8c-8504-11c19536e94a)

**Comment by TudbuT** [comment] 2024-05-17 15:10
The proot distro still sees pressure and tilt present in the Lorie mouse, but as before they do nothing (except now I can actually use gimp with that mouse set to Screen mode, unlike with the old absolute mouse).

**Comment by TudbuT** [comment] 2024-05-17 15:23
Delightful, thank you!

**Comment by twaik** [comment] 2024-05-22 16:54
Do you have a usb tablet which can be connected to PC, with working tilt and rotation axes?

**Comment by TudbuT** [comment] 2024-05-22 18:59
Yes: I have [weylus](https://github.com/H-M-H/Weylus) and also an old XP-Pen tablet lying around *somewhere*.

**Comment by twaik** [comment] 2024-05-23 10:00
AFAIK XP-pen does not support tilt and orientation. And I am not sure if Weylus reports orientation, at least I did not find this part in its code.
Do you know how to check if x tilt, y tilt and orientation are configured right? Probably you know what instruments to use in Gimp? Or other ways?

**Comment by twaik** [comment] 2024-05-23 14:30
@TudbuT @parkerlreed @Revess @Dr4kzor @ephetic @mistune 
Sorry for the ping, but it seems like all of you participated in discussions related to stylus.
Do you have real wacom tablet with x tilt, y tilt and orientation working out of the box?
Or maybe you know how to check if these axes are configured right?
I am implementing the full stylus support but it is a bit hard to test it without knowing how it should behave and without testing on a real device (which I do not have).
Thank you.

**Comment by Revess** [comment] 2024-05-23 16:00
I do have a Wacom Tablet, the Wacom Intuos M Bluetooth Black. I dont know the full capabilities to test. For my tablet I have a samsung Galaxy Tab S8+ with the SPen. Feel free to let me know the pen capabilities. In the last update (last year summer I think) the pen support was working :)

**Comment by twaik** [comment] 2024-05-23 16:05
Do you know how to test tilt and rotation capabilities in Gimp or other software? I need to test if I messed with tilt formulas transforming tilt and rotation from Android to regular X11 format. So I need to know if tilt and rotation behaviour is the same in both cases.

**Comment by twaik** [comment] 2024-05-23 16:09
> In the last update (last year summer I think) the pen support was working :)

Currently termux-x11 supports only transforming android stylus events to X11 mouse events. Currently I am working on real stylus event forwarding, but I need someone who can test it.

**Comment by parkerlreed** [comment] 2024-05-23 16:14
Still have it setup here if you need anything! Thanks.

I can do GIMP with pressure. Samsung doesn't do tilt, angle, or eraser.

**Comment by twaik** [comment] 2024-05-23 16:16
> I can do GIMP with pressure. Samsung doesn't do tilt, angle, or eraser.

It is pretty much weird because currently termux-x11 does not pass stylus pressure to the X server.

Do you know how we can check tilts and orientation? Maybe special Gimp instruments or similar stuff?

**Comment by twaik** [comment] 2024-05-23 18:43
> I do have a Wacom Tablet, the Wacom Intuos M Bluetooth Black.

Can you please post a screenshot of https://patrickhlauke.github.io/touch/tracker/multi-touch-tracker-pointer-hud-pep.html while holding stylus on a tablet? With all the properties it prints?

**Comment by Revess** [comment] 2024-05-23 19:43
Do you want me to do the same thing with the spen and with the wacom pen on the tablet?

**Comment by twaik** [comment] 2024-05-23 19:44
Currently only in chrome on pc with wacom tablet please.

**Comment by Revess** [comment] 2024-05-23 19:49
Sure thing, later today or tomorrow (CET +1) I will try it with the link you provided on my Wacom Tablet!

**Comment by TudbuT** [comment] 2024-05-24 00:59
> Still have it setup here if you need anything! Thanks.
> 
> I can do GIMP with pressure. Samsung doesn't do tilt, angle, or eraser.

It certainly does tilt. Angle I'm not so sure. Here the angle only works when its on the screen. Sketchbook always sees it.
![Screenshot_20240524_025508_Samsung Internet](https://github.com/termux/termux-x11/assets/48156391/8e5a9363-2cdd-4d8e-a0ac-0c7971e64abc)

**Comment by RalfWerner** [comment] 2024-05-24 07:29
**9 seconds stylus.** The stylus touches the screen in second 5. The Samsung menu appears in floating mode and stylus pressure. Which I have done several times in touch mode. **Helpful?**

https://github.com/termux/termux-x11/assets/45426380/31c96a28-7402-4307-8b45-72b454e7caec

**Comment by twaik** [comment] 2024-06-04 11:02
@parkerlreed @Revess @TudbuT 
Can you please test the https://github.com/termux/termux-x11/actions/runs/9365902745 ?

**Comment by twaik** [comment] 2024-06-04 11:04
No, wait. We can not build it since gitlab.freedesktop.org is currently under maintenance and builder can not obtain source code.

**Comment by twaik** [comment] 2024-06-04 12:10
I am not so sure when gitlab.freedesktop.org will be back so there is apk for tests.
[app-universal-debug.zip](https://github.com/user-attachments/files/15551080/app-universal-debug.zip)

**Comment by twaik** [comment] 2024-06-04 12:47
@parkerlreed @Revess @TudbuT can you please test it?

**Comment by twaik** [comment] 2024-06-04 16:50
Ok, https://github.com/termux/termux-x11/actions/runs/9365902745 is available too.

**Comment by TudbuT** [comment] 2024-06-05 19:21
Checking it out now.

**Comment by TudbuT** [comment] 2024-06-05 19:29
![Screenshot_20240605_212928_TermuxX11](https://github.com/termux/termux-x11/assets/48156391/2578b957-7ad2-4d82-9b66-23af53a1db66)
that seems to work perfectly!

**Comment by twaik** [comment] 2024-06-05 19:31
Good. So I think I will fix the bug with device enumeration and after this it will be merged.

**Comment by TudbuT** [comment] 2024-06-05 19:34
perfect! I'll show the device enumeration here:

in proot: ![Screenshot_20240605_213220_TermuxX11](https://github.com/termux/termux-x11/assets/48156391/9142d61a-c4c0-4a8b-bbb0-342ea80a29ad) (this is what i used, works for drawing perfectly.)

in termux directly (DOES NOT WORK FOR DRAWING): 
![Screenshot_20240605_213257_TermuxX11](https://github.com/termux/termux-x11/assets/48156391/d63be8a5-3bde-4f98-9447-5ce81caaee97)

**Comment by twaik** [comment] 2024-06-05 19:35
Termux's gimp should be rebuilt, I opened issue in termux-packages repo.

**Comment by night-nl** [comment] 2024-06-07 13:19
Excellent job! I tested the version, it woked as expected. However, a new problem that  under "Direct touch" mod, my touch event will send the mouse to the top right corner occurs.

**Comment by twaik** [comment] 2024-06-18 05:45
https://github.com/termux/termux-x11/pull/650 so I am closing this. Termux's Gimp problem is not related to termux-x11 plugin so I am closing this.

**Closed by twaik** 2024-06-18 05:45 UTC
