### ISSUE TITLE
[feature request] Ability to zoom in & out...

### ISSUE THREAD

**Issue by bushnest** [termux/termux-x11#669] opened 2024-07-06 20:17 UTC
### Problem description

I am not able to zoom in and out on the screen of Termux-X11.  I tried fiddling with the settings to enable the ability to do that, but am still unable to do that.  Is that ability currently non-existent or is there something that I'm doing wrong?  Thx.

### What steps will reproduce the bug?

n/a

### What is the expected behavior?

The ability to pinch zoom the screen in and out.

**Comment by knyipab** [comment] 2024-07-07 01:02
Alt + Scroll?

**Comment by twaik** [comment] 2024-07-07 04:43
Duplicate of #597

**Closed by twaik** 2024-07-07 04:43 UTC
