### ISSUE TITLE
[Bug]: termux-x11 throws an unhandled exception

### ISSUE THREAD

**Issue by rasp0wn** [termux/termux-x11#523] opened 2023-12-20 15:50 UTC
### Problem description

I have a Lenovo Legion Y700 (v2022) tablet where I can't execute termux X11 because of an unhandled exception thrown. I have done the same steps in a Xiaomi Mi Pad 5 and I can run termux-x11 without problems so I'm not sure about what could be the issue. 

This is the exception: 
![image](https://github.com/termux/termux-x11/assets/68296250/b5a41bd1-fa07-49d1-b5fd-a998ea7e8c19)

```
java.lang.ExceptionInInitializerError
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at com.termux.x11.Loader.main(Loader.java:24)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:403)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Configuration android.app.ActivityThread.getConfiguration()' on a null object reference
        at com.termux.x11.CmdEntryPoint.createContext(CmdEntryPoint.java:189)
        at com.termux.x11.CmdEntryPoint.<clinit>(CmdEntryPoint.java:39)
        ... 5 more
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Configuration android.app.ActivityThread.getConfiguration()' on a null object reference
        at android.view.Display.getMetrics(Display.java:1154)
        at android.app.ResourcesManager.getDisplayMetrics(ResourcesManager.java:256)
        at android.app.ResourcesManager.getDisplayMetrics(ResourcesManager.java:244)
        at android.app.ContextImpl.createSystemContext(ContextImpl.java:2640)
        at android.app.ActivityThread.getSystemContext(ActivityThread.java:2571)
        at com.termux.x11.CmdEntryPoint.createContext(CmdEntryPoint.java:187)
```

I have tried to install different versions of termux and termux-x11 applications and I always get the same exception every time I try to run termux-x11. This is what I'm trying to do: 
```
pkg install tur-repo
pkg install x11-repo
pkg install termux-x11-nightly
pkg install xfce4
apt install xfce4-session

export DISPLAY=:0
termux-x11 :0 &
```

### What steps will reproduce the bug?

When executing the "termux-x11" command an exception occurs

### What is the expected behavior?

I would like to be able to use termux-x11 on my device

**Comment by twaik** [comment] 2023-12-20 15:52
Duplicate of #518

**Closed by twaik** 2023-12-20 15:52 UTC

**Comment by twaik** [comment] 2024-03-26 05:53
Probably that can be fixed by OLD_CONTEXT option from [build 594](https://github.com/termux/termux-x11/actions/runs/8431417771).
Install it and try `OLD_CONTEXT=1 termux-x11 :0 -xstartup xfce4-session`.
