### ISSUE TITLE
[Bug]: Termux freezing after termux-x11 :1, exiting and reopening causes this issue

### ISSUE THREAD

**Issue by GuythatUhmCreatesRandomStuff** [termux/termux-x11#485] opened 2023-10-15 13:42 UTC
### Problem description

xWayland takes like alot longer than it should

### What steps will reproduce the bug?

~ $: termux-x11 :1
_XSERVTransSocketUNIXCreateLissener: …SocketCreateListener() failed
_XSERVTransMakeAllCOTSServerListeners server already running(EE)
Fatal server error:
Cannot establish any listening sockets, please close any x server that is running

### What is the expected behavior?

not be able to use proot distro as a gui

**Comment by twaik** [comment] 2023-10-15 13:47
Duplicate of #484

**Closed by twaik** 2023-10-15 13:47 UTC
