### ISSUE TITLE
[Bug]: Exception: Only one Looper may be created per thread

### ISSUE THREAD

**Issue by vank4o** [termux/termux-x11#553] opened 2024-02-08 18:58 UTC
### Problem description

When I run termux-x11 in termux, the command immediately exits with
java.lang.ExceptionInInitializerError
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:536)
        at com.termux.x11.Loader.main(Loader.java:24)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:398)
Caused by: java.lang.RuntimeException: Only one Looper may be created per thread
        at android.os.Looper.prepare(Looper.java:116)
        at android.os.Looper.prepareMainLooper(Looper.java:130)                                                             at com.termux.x11.CmdEntryPoint.<clinit>(CmdEntryPoint.java:221)                                                    ... 5 more

Running with TERMUX_X11_DEBUG=1 doesn't provide any additional information

![Screenshot_20240208_195018](https://github.com/termux/termux-x11/assets/127669382/7bad7b1b-2b1a-410c-89ae-6533080986fe)

### What steps will reproduce the bug?

Run the command termux-x11 on the command prompt

### What is the expected behavior?

Successfully start termux-x11

**Comment by twaik** [comment] 2024-02-08 18:59
Where exactly did you get apk and deb?

**Comment by twaik** [comment] 2024-02-08 19:03
@vank4o ?

**Comment by vank4o** [comment] 2024-02-08 19:11
I've got it from Build Actions(latest)

**Comment by twaik** [comment] 2024-02-08 19:29
I am asking about both `.apk` and `.deb` packages.
I tried installing both from the last action and it works.

The problem you mentioned can happen only if you use old outdated `.deb` with new `.apk`. Period.

Duplicate of #551.

**Closed by twaik** 2024-02-08 19:29 UTC

**Comment by vank4o** [comment] 2024-02-08 19:51
No, it's definitely not done! I've installed termux-x11-nightly-1.03.00-0-all.deb as well as the universal apk from the same build on my Honor phone and on my lenovo tablet. On my tablet it works, on my phone it exits with the Exception. How is this possible?! Both are on android 13. 


![Screenshot_20240208-210745](https://github.com/termux/termux-x11/assets/127669382/a3354ddd-6887-4148-a8ae-5cf6a6eb5451)

**Comment by twaik** [comment] 2024-02-08 20:12
Try that one. https://github.com/termux/termux-x11/actions/runs/7835283475

I have no idea why this line causes exception even with guarding expression. This build explicitly ignores it.

**Comment by twaik** [comment] 2024-02-08 21:18
@vank4o does it work?

**Comment by twaik** [comment] 2024-02-09 11:51
@vank4o ?

**Comment by vank4o** [comment] 2024-02-09 14:13
> Try that one. https://github.com/termux/termux-x11/actions/runs/7835283475
> 
> I have no idea why this line causes exception even with guarding expression. This build explicitly ignores it.

Hello Twaik,

Sorry I just saw your reply. I could test it  and it works just like on my tablet. Thank you very much!

Yesterday I tared my entire termux setup from the lenovo tablet, I dumped the apks for termux and termux-x11 and transferred them to the Honor phone, but I still got the exception. Maybe it's something with the Kernel or some libs on this particular phone... Maybe because it is a foldable. I don't know. Thank you again!

**Comment by twaik** [comment] 2024-02-09 14:15
Do you get exception with the apk from [latest artifact](https://github.com/termux/termux-x11/actions/runs/7835283475)? This new version simply ignores this exception so it should work.

**Comment by twaik** [comment] 2024-02-09 20:52
@vank4o ?

**Comment by twaik** [comment] 2024-02-11 07:11
@vank4o ?

**Comment by vank4o** [comment] 2024-02-13 00:07
Hello twaik,

yes, it does work, I don't get any exceptions. Thank you!
