### ISSUE TITLE
Physical right mouse button is not registered

### ISSUE THREAD

**Issue by xu3s** [termux/termux-x11#355] opened 2023-06-19 15:35 UTC
While using the app when trying to right click it does not get registered, is this can be fixed or is there currently no work around this?

And also middle click just go to home

My devices running android 11 aarch64 if that matter.

**Comment by twaik** [comment] 2023-06-19 22:14
I need to know what application prints in debug mode when you try to make a right click.

I already wrote all necessary code to handle right click. But some devices simply do not let intercept it. There is no fix for this.

**Comment by xu3s** [comment] 2023-06-20 00:06
Here is the log [termux-x11.log](https://pastebin.com/femY45CC)

**Comment by twaik** [comment] 2023-06-20 00:08
Is it the whole log? I do not see any click attempts or even Termux:X11 app connection...

**Comment by xu3s** [comment] 2023-06-20 01:22
Thats the only log that i get by running `env TERMUX_X11_DEBUG=1 termux-x11 :0 > tmx11.log &` is this wrong?

**Comment by twaik** [comment] 2023-06-20 01:23
Did you interact with the program after running this?

**Comment by xu3s** [comment] 2023-06-20 01:26
Yes, i run xfce4-session on another tab. Then i tried opening  some apps and click and right click there.

**Comment by twaik** [comment] 2023-06-20 01:27
It is pretty weird, program must show much more lines...

**Comment by xu3s** [comment] 2023-06-20 01:45
I'll try again later, i need to go now

**Comment by xu3s** [comment] 2023-06-20 13:41
can this be a reason why the logs is incomplete???

```
~ $ env TERMUX_X11_DEBUG=1 termux-x11 :0 > tmx11.log
logcat: Unexpected EOF!

This means that either the device shut down, logd crashed, or this instance of logcat was unable to read log
messages as quickly as they were being produced.

If you have enabled significant logging, look into using the -G option to increase log buffer sizes.
logcat: Unexpected EOF!

This means that either the device shut down, logd crashed, or this instance of logcat was unable to read log
messages as quickly as they were being produced.

If you have enabled significant logging, look into using the -G option to increase log buffer sizes.
```

**Comment by twaik** [comment] 2023-06-20 13:43
Unknown...

**Comment by xu3s** [comment] 2023-06-20 13:46
so , there is nothing i coud do here???

**Comment by twaik** [comment] 2023-06-20 13:47
I can not reproduce this and do not know what to do.

**Comment by twaik** [comment] 2023-06-22 18:32
So can you try again with TERMUX_X11_DEBUG to catch this?

**Comment by xu3s** [comment] 2023-06-22 23:57
Unfortunately no, i have tried to restart my phone, and even upgraded my os to android 13 that i push back againts still same error: 
`
logcat: Unexpected EOF!
This means that either the device shut down, logd crashed, or this instance of logcat was unable to read logmessages as quickly as they were being produced.If you have enabled significant logging, look into using the -G option to increase log buffer sizes.`
I even increases the log buffer size to 100M still the same. 

Searching on google still no luck

**Comment by ThatMG393** [comment] 2023-06-23 00:20
@xu3s try clearing data of termux x11

**Comment by twaik** [comment] 2023-06-23 06:12
Termux:X11 does nkt keep any data, nothing to be cleared. But it is possible to obtain logs via ADB.

**Comment by xu3s** [comment] 2023-06-23 08:38
> Termux:X11 does not keep any data, nothing to be cleared. But it is possible to obtain logs via ADB.

Can you tell me how to do that?

**Comment by twaik** [comment] 2023-06-23 10:51
Just google how to use ADB.

**Comment by twaik** [comment] 2023-06-24 13:29
Any news on this?

**Comment by ask9027** [comment] 2023-06-25 15:47
> Any news on this?

everything is working fine

**Comment by twaik** [comment] 2023-06-25 15:47
I was asking @xu3s.

**Comment by ask9027** [comment] 2023-06-25 15:47
> I was asking @xu3s.

okay

**Comment by xu3s** [comment] 2023-06-25 15:58
sorry, been trying to figure out how to use logcat 

trying this command: `adb logcat ActivityManager:I com.termux.x11:D *:S` but it give no info can someone guide me or just link  me to some article about this if possible

**Comment by twaik** [comment] 2023-06-25 16:01
`adb logcat -c` to clear log, start `termux-x11 :0 & echo pid is $!` and after having `aborted` message use `adb logcat <pid>` with pid number you see after starting termux-x11...

**Comment by xu3s** [comment] 2023-06-25 16:16
![Screenshot_2023_0625_231017.jpg](https://github.com/termux/termux-x11/assets/47383486/80a845aa-1c8b-46aa-a5ce-bbd345f6751e)

this is the only thing i got running the command suggested:
```
~ $ adb logcat -c
~ $ termux-x11 :0 & echo pid is $!
[1] 14004
pid is 14004
~ $ adb logcat 14004
--------- beginning of main
06-25 23:08:42.556 18252  8076 E BufferQueueProducer: [SurfaceView[com.termux.x11/com.termux.x11.MainActivity]#18(BLAST Consumer)18](id:474c00000012,api:1,p:14004,c:18252) query: BufferQueue has been abandoned
06-25 23:08:42.556 18252  8076 E BufferQueueProducer: [SurfaceView[com.termux.x11/com.termux.x11.MainActivity]#18(BLAST Consumer)18](id:474c00000012,api:1,p:14004,c:18252) query: BufferQueue has been abandoned
06-25 23:08:42.573 18252  8076 E BufferQueueProducer: [SurfaceView[com.termux.x11/com.termux.x11.MainActivity]#18(BLAST Consumer)18](id:474c00000012,api:1,p:14004,c:18252) connect: BufferQueue has been abandoned
```

i run xfce on another session and open termux:X11 app and clicking on it with my mouse, that is the only output.

i'm starting to think that this problem only occur on my device which is 
**vivo t1 5g** (anyone with this specific device please help)

**Comment by twaik** [comment] 2023-06-25 16:18
Sorry, I was wrong, `adb logcat --pid=<pid>`

**Comment by xu3s** [comment] 2023-06-25 16:29
![Screenshot_2023_0625_232802.jpg](https://github.com/termux/termux-x11/assets/47383486/a4c806df-bef4-43aa-a0d4-3a7239a5156e)

now there is no output

```
~ $ adb logcat -c
~ $ env TERMUX_X11_DEBUG=1 termux-x11 :0 &                                 [1] 18884                                                                  ~ $ logcat: Unexpected EOF!                                                
This means that either the device shut down, logd crashed, or this instance of logcat was unable to read log                                          messages as quickly as they were being produced.                           
If you have enabled significant logging, look into using the -G option to increase log buffer sizes.                                                  logcat: Unexpected EOF!                                                    
This means that either the device shut down, logd crashed, or this instance of logcat was unable to read log                                          messages as quickly as they were being produced.                           
If you have enabled significant logging, look into using the -G option to increase log buffer sizes.                                                  pidof logcat: Unexpected EOF!                                              
This means that either the device shut down, logd crashed, or this instance of logcat was unable to read log                                          messages as quickly as they were being produced.                           
If you have enabled significant logging, look into using the -G option to increase log buffer sizes.                                            env TERMUXadb logcat --pid=18884                                                 logcat: Unexpected EOF!
                                                                           This means that either the device shut down, logd crashed, or this instance of logcat was unable to read log                                          messages as quickly as they were being produced.
                                                                           If you have enabled significant logging, look into using the -G option to increase log buffer sizes.                                                  ^C
~ $
```

**Comment by twaik** [comment] 2023-06-25 16:29
`adb logcat --pid=<pid>` ...

**Comment by xu3s** [comment] 2023-06-25 16:30
maybe my logcat is faulty? it seems like the logcat is crashing when trying to output the log.

**Comment by twaik** [comment] 2023-06-25 16:33
You have started `env TERMUXadb logcat --pid=18884`, not `adb logcat --pid=18884`...

**Comment by xu3s** [comment] 2023-06-25 16:33
> `adb logcat --pid=<pid>` ...

yeah i have run it there but it got buried by the error log of logcat instead, you can see that i run the `logcat --pid=pid` after i run termux-x11 in the background

**Comment by twaik** [comment] 2023-06-25 16:34
`logcat --pid` does not fit here. That was a reason I adviced you to use ADB and not logcat directly.

**Comment by xu3s** [comment] 2023-06-25 16:36
> You have started `env TERMUXadb logcat --pid=18884`, not `adb logcat --pid=18884`...

that is because i scroll through my recent command, and that does not have a side effect on the command that i run, you can try yourself when you run comand in bg that throw stuff and scroll though history and running it

**Comment by twaik** [comment] 2023-06-25 16:37
Start it in another session.

**Comment by xu3s** [comment] 2023-06-25 16:49
ok,
sorry this is midnight here need to sleep, i have to work tomorrow.

Tomorrow I'll attach a video o you can see what i see, or i can do sharescreen on discord my handle is exelroad

**Comment by Miguelgrubert** [comment] 2023-06-27 00:28
Ola poderia falar comigo em português

Em dom., 25 de jun. de 2023 12:49, xu3s ***@***.***> escreveu:

**Comment by twaik** [comment] 2023-06-27 06:51
Official language of this repo is English.

**Comment by xu3s** [comment] 2023-06-30 15:47
this is the
[screen recording](https://drive.google.com/file/d/1TnHtouAFF19JbvTN1cpoCHtu4yH0axWW/view?usp=drivesdk) of what i get , please enlighten me.

**Comment by xu3s** [comment] 2023-07-03 11:09
I don't mind. How should i help you to do that?

**Comment by twaik** [comment] 2023-07-03 11:11
Contact me in Discord. `.twaik`

**Comment by xu3s** [comment] 2023-07-03 11:13
Ok, mine is `exelroad`

**Comment by kulturguda** [comment] 2023-07-04 16:16
Middle (scroll) and right click do not work for me either. `TERMUX_X11_DEBUG=1 termux-x11 :0` registers left click, but neither middle nor right click. Now I'm making right click with double tap or VNC as a solution.

**Comment by twaik** [comment] 2023-07-05 06:21
It looks like there is no way to intercept middle and right clicks on such devices. Or I failed to find such a way.

**Closed by twaik** 2023-07-05 06:21 UTC
