### ISSUE TITLE
The display delay is relatively serious

### ISSUE THREAD

**Issue by yuxue521** [termux/termux-x11#12] opened 2020-04-23 09:19 UTC
xwayland 
The display delay is more serious, weston-simple-egl only has 20fps, and the memory usage is very large

**Comment by Grimler91** [comment] 2020-04-23 09:21
Feel free to contribute patches, this addon is unmaintained as noted on the [main page](https://github.com/termux/termux-x11)

**Comment by twaik** [comment] 2020-04-23 09:50
Any wayland/x11 apps can not use GLES/EGL due to Android restrictions. Software rendering is used.

**Comment by suhan-paradkar** [comment] 2021-09-04 15:25
Closing since this can't be reproduced as of now...

**Closed by suhan-paradkar** 2021-09-04 15:25 UTC
