### ISSUE TITLE
[Proposal]: X11 Multiwindow support

### ISSUE THREAD

**Issue by IntinteDAO** [termux/termux-x11#715] opened 2024-08-30 20:05 UTC
### Problem description

I don't know if this is possible in the Android environment. This is a feature that all sorts of X Servers have (for Windows, some for Linux). In a nutshell, it consists in the fact that the X server runs in the background, so to speak, and each application is somehow transmitted separately.

It is potentially possible to run applications with separate sockets, although it usually runs all on one.

In a nutshell, it looks as if each application is running on a "real" system, instead of running a full X server with a session.

Such a thing will (potentially) reduce resources and increase the imersion of using the application.

![obraz](https://github.com/user-attachments/assets/e25ef406-93f2-40af-9665-c1a361f3910c)
![obraz](https://github.com/user-attachments/assets/beddd33c-8d42-41da-930c-49588bf5d2b1)
^ Examples

### What steps will reproduce the bug?

x

**Comment by Biswa96** [comment] 2024-08-30 20:10
Have you tried any window manager or desktop environment in termux-x11? More info at https://wiki.termux.com/wiki/Graphical_Environment

**Comment by twaik** [comment] 2024-08-30 20:13
Android Window system integration is not possible due to a lot of differences between Android and regular Linux distro windowing systems and restrictions of Android windowing system itself.
Examples:
1. There is no API to switch between fullscreen and freeform mode.
2. There is no API to create windows. The only thing you can create is a Task which will be represented in Recents screen or on taskbar in the case of desktop mode or Samsung Dex.
3. There is no classic taskbar on Android devices, only Recents screen. Also there is no system tray, it was replaced by notification bar and notification drawer in Android.
4. There is no API for controlling window size and position in freeform mode.
5. It is not possible to control window decorations in freeform mode.
6. It is not possible to control or even get properties like size and position of other windows.
7. It is not possible to change window caption and icon in freeform mode and in Recents screen.
And so on.

Not going to be implemented.

**Comment by TomJo2000** [comment] 2024-08-30 20:14
Yep window management is an issue for a window manager to handle (as the name would suggest).
Its out of scope for Termux:X11 itself to handle that when we package a dozen different window managers whose whole deal is managing X windows.

**Closed by twaik** 2024-08-30 20:13 UTC

**Comment by IntinteDAO** [comment] 2024-08-30 21:51
> Have you tried any window manager or desktop environment in termux-x11? More info at https://wiki.termux.com/wiki/Graphical_Environment

Yep, but you are "isolated" from Android Desktop. In Multiwindow mode you can work on Linux apps and Android in the same time (in theory).



> Android Window system integration is not possible due to a lot of differences between Android and regular Linux distro windowing systems and restrictions of Android windowing system itself. Examples:
> 
>     1. There is no API to switch between fullscreen and freeform mode.
> 
>     2. There is no API to create windows. The only thing you can create is a Task which will be represented in Recents screen or on taskbar in the case of desktop mode or Samsung Dex.
> 
>     3. There is no classic taskbar on Android devices, only Recents screen. Also there is no system tray, it was replaced by notification bar and notification drawer in Android.
> 
>     4. There is no API for controlling window size and position in freeform mode.
> 
>     5. It is not possible to control window decorations in freeform mode.
> 
>     6. It is not possible to control or even get properties like size and position of other windows.
> 
>     7. It is not possible to change window caption and icon in freeform mode and in Recents screen.
> 
> 
> And so on.
> 
> Not going to be implemented.

Sure, I assumed the introduction of this mode precisely for solutions like DeX or Ready Now. That is, "somehow" the user launches two applications and each application is a separate application. I don't know if Android allows you to run the same app twice, if not it probably wouldn't work. If so, X Server would have to multiply its process and display in one window, one application.

**Comment by twaik** [comment] 2024-08-31 07:04
Again, there is no API for this.

**Comment by IntinteDAO** [comment] 2024-09-09 05:27
@twaik 
Hmm, is it possible to run multiple Termux X11 Windows on Android (via cli probably) and set a custom DISPLAY for every ... client?

**Comment by twaik** [comment] 2024-09-09 06:06
It is not...

**Comment by IntinteDAO** [comment] 2025-03-15 19:34
@twaik 

Termux GUI can handle multiple instances somehow. Maybe TX11 can also somehow?

**Comment by twaik** [comment] 2025-03-15 20:39
No.

**Comment by twaik** [comment] 2025-12-16 05:28
Integrating termux-x11 into Android's window management system IS possible. But the problem is that Android does not let us nor create taskbar icons for different "windows", nor add/remove window decorations (including minimize/maximize/close buttons), nor even control the window size.
So you can not even control your windows from termux side. It will break lots of programs and will require a lot of time and effort, I am not going to implement it.

**Comment by RalfWerner** [comment] 2025-12-19 18:51
@IntinteDAO, I don't understand your question and your shot. Are you aware that you are here in a Termux (Android) forum and **not** MS Windows? Maybe someone else can help you or you're looking for another forum.

**Comment by twaik** [comment] 2025-12-19 18:56
I am bad at writing long detailed texts in English so I used AI for that, sorry.

---

A "seamless" desktop-like integration into Android is theoretically possible, but in practice Android imposes hard architectural limits. Without system-level privileges, it is not possible to simultaneously achieve Win/Linux-style window management and full integration with the Android window manager (freeform / DeX).

## 1. Activity-based integration (Android WM / freeform / DeX) 

#### Model

* Each Linux / Wayland application window is hosted inside an Android Activity.
* Activities run in freeform mode (or DeX where available).
* Android’s window manager controls placement, resize, z-order, and task switching.

#### Advantages

* Native integration with Android WM.
* Windows participate in system z-order, overview, and alt-tab/task switching.
* Works in DeX and large-screen freeform modes.
* Proper focus handling, input method integration, and lifecycle management.
* No root, no hidden APIs, no overlay permissions required.

#### Limitations

* Activities cannot freely control their window size or position.
* Applications cannot prevent user-initiated resizing of freeform windows.
* There are no true system-level modal windows; dialogs are always confined to an Activity’s bounds.
* Android does not expose a proper, desktop-style taskbar on phones, and behavior on tablets and OEM shells is inconsistent.
* It is currently undefined whether multiple Activity aliases belonging to the same app will be grouped together or treated as separate tasks in the system UI; this behavior varies by Android version and OEM and cannot be controlled programmatically.
* Launcher icons and labels are static; dynamic per-window icons are not supported (only predeclared Activity aliases or pinned shortcuts).
* Window behavior and constraints differ significantly across Android versions and OEM implementations.

#### Conclusion
This approach provides the maximum officially supported integration with Android, but it cannot replicate the level of window control expected from Win/Linux window managers.

## 2. Custom window manager using system overlays

#### Model

* The application renders and manages its own windows using system overlays (SYSTEM_ALERT_WINDOW).
* Window placement, size, modality, and stacking are fully controlled by the application.

#### Advantages

* Full control over window geometry and behavior.
* True modal windows, fixed-size windows, tiling, and stacking are possible.
* Behavior can closely resemble X11/Wayland window managers.

#### Limitations

* Overlay windows are not Android tasks and do not participate in the system window manager.
* No integration with system z-order, overview, alt-tab, or DeX task management.
* Input focus, IME interaction, and security behavior are fragile and inconsistent.
* Overlay permissions significantly degrade user experience and app acceptance.
* Overlay behavior is increasingly restricted in newer Android versions.

#### Conclusion
This produces a desktop-like UI, but it exists outside the Android window manager and behaves as a separate, non-system layer.

## 3. Why these approaches cannot be combined

* Only the system window manager can own tasks and control their bounds.
* Third-party applications cannot create or manage Task or WindowContainer objects.
* Activities receive resize events but cannot authoritatively control them.
* Surfaces can only be exchanged reliably between Android components, not arbitrary Linux processes.
* Any deeper integration requires hidden APIs or framework modification.

This is a platform limitation, not an implementation choice.

## 4. Root and system-level modifications

Even with root access, Android does not expose stable APIs for creating true system-managed windows comparable to Win/Linux. Achieving deeper integration typically requires framework hooks (e.g., LSPosed or similar runtime modification), which:

* Are device-specific and fragile across updates.
* Are unacceptable for many users.
* Conflict with the goal of running in a non-rooted environment.

Projects like Termux are explicitly designed to work without root, making such approaches out of scope.

## 5. Practical compromise

The only robust, non-root approach is:

* Use Android Activities as window containers.
* Let Android WM handle placement and resizing.
* Run the Linux/Wayland stack inside those containers.
* Implement desktop-like behavior (dialogs, focus rules, layout) inside the content, not via Android WM.

## Final conclusion
A fully seamless Win/Linux-style desktop experience is not achievable on Android without system-level privileges.

* Prioritizing Android integration requires accepting Activity-level constraints.
* Prioritizing desktop-style window control sacrifices integration with Android WM.
* This trade-off is inherent to the Android platform and cannot be resolved purely at the application level.

---

Given the amount of engineering effort required and the fundamental UX limitations imposed by Android, implementing a solution that is even remotely comparable to a traditional desktop environment would require a very large and long-term investment. Even then, the result would still be constrained by platform behavior outside the project’s control.

For these reasons, this is not something I realistically plan to implement within this project. If such an experiment were ever attempted, it would most likely be based on Wayland rather than X11 and developed as a completely separate application, outside the scope and goals of this repository.

Again, sorry for AI.

**Comment by twaik** [comment] 2025-12-26 05:28
Multiwindow is not related to multiple tasks in taskbar. 
IIRC Dex grouped termux:x11's settings activity and main window activity icons into one group and there was no way to separate them. And it will be a problem.

**Comment by robertkirkman** [comment] 2026-02-16 22:08
> - Activities cannot freely control their window size or position.
> - Applications cannot prevent user-initiated resizing of freeform windows.
> - There are no true system-level modal windows; dialogs are always confined to an Activity’s bounds.
> - Android does not expose a proper, desktop-style taskbar on phones, and behavior on tablets and OEM shells is inconsistent.
> - It is currently undefined whether multiple Activity aliases belonging to the same app will be grouped together or treated as separate tasks in the system UI; this behavior varies by Android version and OEM and cannot be controlled programmatically.
> - Launcher icons and labels are static; dynamic per-window icons are not supported (only predeclared Activity aliases or pinned shortcuts).
> - Window behavior and constraints differ significantly across Android versions and OEM implementations.

@IntinteDAO I'm not sure if you saw my message in matrix so just in case you didn't see it, I wanted to let you know that even despite those limitations there is someone who is making it anyway and their version is based on Xwayland (like how early version of Termux:X11 was also based on Xwayland) but theirs is different and it's not released yet but there is a screenshot

<img width="1800" height="1125" alt="Image" src="https://github.com/user-attachments/assets/185b838a-d34d-47f2-8821-e0fbc6864d49" />

**Comment by nicman23** [comment] 2026-06-25 09:10
@robertkirkman could you please give the repo name if the other developer released it

**Comment by robertkirkman** [comment] 2026-06-25 09:14
The person who made that took a break currently and I don't know when they will finish or release that, but, in the discord a lot of other people are working on wayland things with multiple monitors support, so if you are interested you can join discord and check what they are talking about. i don't know if any of those things are finished either though.

**Comment by robertkirkman** [comment] 2026-06-25 09:15
This is one of the repos people were talking about but I have no idea how to use it or if it's finished yet: https://github.com/Vower2993/WayLandIE

**Comment by robertkirkman** [comment] 2026-07-11 13:49
Someone recently independently discovered, or also found through my guide, my method (appears to be duplicated Termux:X11 or simply multiple Termux:X11 main activity windows)

<img width="900" alt="Image" src="https://github.com/user-attachments/assets/2b931ecd-0d33-4cc2-8cbc-7f7ec21870c0" />

comparison to the screenshot I posted above of my method, so any similarity or difference is clear:

<img width="300" alt="Image" src="https://github.com/user-attachments/assets/0a08f3ce-7af2-48d6-9fa8-e26f8326c214" />

**Comment by robertkirkman** [comment] 2026-07-11 13:58
> [@robertkirkman](https://github.com/robertkirkman) could you please give the repo name if the other developer released it

@nicman23 also the person who created this recently returned and posted a small update message and new content which I am copying here for you to see:

<img width="300" alt="Image" src="https://github.com/user-attachments/assets/536bbc74-d9da-4120-a239-bd57248c3d5a" />

<img width="1745" height="1091" alt="Image" src="https://github.com/user-attachments/assets/3aaaf0e2-084c-4f35-bc7a-3da24e49bcce" />

it is evidence of a Termux Wayland Firefox with working GPU acceleration,

they still haven't released code yet.

**Comment by nicman23** [comment] 2026-07-11 18:42
that is great! thanks a lot <3
