### ISSUE TITLE
InterceptorKey not working in most cases

### ISSUE THREAD

**Issue by IntinteDAO** [termux/termux-x11#418] opened 2023-08-07 21:03 UTC
I do not know what data is needed. Well, on the Moto G100 it seems that InterceptorKey works very infrequently and is easily disabled. I don't know what realistically depends on whether it works properly or not.

In my opinion, this function should work when the mouse is "captured" by Termux X11 and disable when the mouse is "released" to Android.

Unfortunately, I had quite a problem with the operation, which I put in the video. Maybe I misunderstand the operation of this function.

Log (very big ... sorry)
https://notebin.de/?45deb54a519fd342#G6dfkwaxYhbe4bSiPoeasBsk7mWtsQpBHypXn4P8WT4M

Movie:
https://tube.midov.pl/w/vb8camrqsPNsUdwx13kYsL

**Comment by twaik** [comment] 2023-08-07 21:13
Do you enable it manually or through Accessibility settings?

**Comment by twaik** [comment] 2023-08-07 22:02
Check the latest build.

**Comment by IntinteDAO** [comment] 2023-08-08 12:25
Maybe partially fixed, but not fully

https://cpaste.org/?90051cf7b3ab1367#4fKxbLtZ3DKCLid2dscaZHrDHhsmKa1czDj8HLSPJBYD

1) Auto Interceptor doesn't work, you have to manually launch on my phone.
2) It works usually nice, but some tasks can disable Interceptor, like notifications, sometimes minimize etc

Movie: 
https://tube.midov.pl/w/xbGqLyhZsdbdkNaXscKh1i

**Comment by twaik** [comment] 2023-08-08 13:48
KeyInterceptor should work only when Termux:X11 activity is focused.

**Comment by twaik** [comment] 2023-08-08 14:15
Why are you going to settings through package settings? You have a shortcut.
![image](https://github.com/termux/termux-x11/assets/9674930/476edb0a-3373-47d4-bd93-6529ab6462d8)

**Comment by twaik** [comment] 2023-08-08 14:46
> Yep, I should report it. Doesn't work with Adaway (or just doesn't work). If I choose Preferences, I received Adaway Preferences instead Termux X11 (but only on Desktop Mode)

It is pretty weird, I did not found any information about it. Maybe it is some kind of firmware-related bug.

Ok, now it should send intercepted events only when activity is really focused.
[app-arm64-v8a-debug.zip](https://github.com/termux/termux-x11/files/12292632/app-arm64-v8a-debug.zip)

**Comment by IntinteDAO** [comment] 2023-08-08 16:23
> @IntinteDAO ?

Sorry, I think the USB-C cable is dead and I can't check it now ;( Give me ~1h

**Comment by IntinteDAO** [comment] 2023-08-08 17:03
@twaik Sadly it's even worse I think?
https://pastebin.linqhost.nl/?1649915eda4c0fef#DrF7seRqq1AWZYLcT74gGZbUp3GjA5XmcebMXXXpvtEF

Do you need movies or just log?

**Comment by twaik** [comment] 2023-08-08 17:09
Ok, I see an exception.

**Comment by twaik** [comment] 2023-08-08 17:11
[app-arm64-v8a-debug.zip](https://github.com/termux/termux-x11/files/12294165/app-arm64-v8a-debug.zip)
Try this one.

**Comment by twaik** [comment] 2023-08-08 17:13
[app-arm64-v8a-debug.zip](https://github.com/termux/termux-x11/files/12294175/app-arm64-v8a-debug.zip)

**Comment by twaik** [comment] 2023-08-08 17:44
![image](https://github.com/termux/termux-x11/assets/9674930/2981176b-587e-422a-a490-51c1aa493d4c)

**Comment by IntinteDAO** [comment] 2023-08-08 17:46
@twaik Sorry, but maybe this file was too big (7MB), it's logcat
https://paste.tildeverse.org/?2ee4fc9941040e91#947oRQGmx8zupQGXwymBrgoWrBuGgJWqrMxj5HKd6ugi

**Comment by twaik** [comment] 2023-08-08 18:18
[app-arm64-v8a-debug.zip](https://github.com/termux/termux-x11/files/12294657/app-arm64-v8a-debug.zip)

**Comment by IntinteDAO** [comment] 2023-08-08 18:46
Ok, no crashing, but only manual InterceptorKey enable works. Auto doesn't work. It's enabled in accessibility menu, but with status "Not working. Click to get info", but there is no info

I don't think there is something in the log about it, but maybe you will find something in logcat.

But the manual works flawlessly

https://privatebin.arch-linux.cz/?91db457aded2e1c1#6bpUYPvXDhWgqVv2K6Jhb2k21ZGdBs18Y9oRneD5uEYS

**Comment by twaik** [comment] 2023-08-08 18:54
Unfortunately I did not find the cause of this in logcat. Sad.
So I am merging this.

**Comment by twaik** [comment] 2023-08-08 18:55
@zanfix @xaverm can you please test if the binary has correct German layout handling?

**Comment by IntinteDAO** [comment] 2023-08-08 18:58
> Unfortunately I did not find the cause of this in logcat. Sad. So I am merging this.

Can this only be managed at the phone's autostart?  Can Termux itself turn on the Interceptor? Because maybe this way can be bypassed somehow.

If not, too bad :P

**Comment by twaik** [comment] 2023-08-08 19:00
@IntinteDAO Maybe we can do something else. Can you please do the following?
1. Enter LoriePreferences and disable automatic enabling of accessibility service.
2. Make system-wide `logcat -c` to clear logcat buffers.
3. Enable automatic enabling of accessibility service.
4. Get logcat.

Clearing logcat buffers should let you get shorter log. Reading 4.1 MB of logs is not the funniest thing in the world, searching there keywords like `KeyInterceptor` and `Accessibility` also did not work.

**Comment by twaik** [comment] 2023-08-08 19:08
Actually I have an idea.
[app-arm64-v8a-debug.zip](https://github.com/termux/termux-x11/files/12295036/app-arm64-v8a-debug.zip)
Check it out.

**Comment by IntinteDAO** [comment] 2023-08-08 19:31
Not working ;( I reduced a little of logcat, but not sure if it has something
https://paste.hostux.net/?6fb221b962770f8f#26YK5NS3EQMZV5EUHNJgtTDtadTfidQDfF2GmsXE5QKP

**Comment by twaik** [comment] 2023-08-08 19:39
No data related to the cause of issue in this log.

Try the following thing.
1. Disable KeyInterceptor in Accessibility Settings.
2. Do `settings list secure` in adb shell and save to a file.
3. Enable KeyInterceptor in Accessibility Settings. 
4. Do `settings list secure` in adb shell again and save to a second file.
5. Post here both files.

Maybe I simply can enable something else to fix this, but I will not know what exactly without these two files.

**Comment by IntinteDAO** [comment] 2023-08-08 19:56
Ok. Maybe it's useful, maybe not, but if I disable and enable button for automatical, I received an error in Termux X11 log. Maybe it should be there.

https://pastebin.linqhost.nl/?73c03dc0d9060b08#GSxdajVUQpXPcpgXzgfgQNc8FKzt6n2P28Bs6N5jo1EW

Anyway, now in Accessibility I have that Termux X11 KeyInterceptor works (but it isn't in Termux X11).
___

Settings List Secure:
Disable: https://bin.0xfc.de/?aebdb062d59d0e66#24P5YhHwxidbio4juheUDd7a6FiYBWu1s8o39nafoDen
Enable: https://bin.0xfc.de/?353bfc82f4331534#BH7nTHkwC1c2gGTddvmXuNhZY6mZmzpD269RH5knJhZr

**Comment by IntinteDAO** [comment] 2023-08-08 20:11
@twaik Found a probably solution
In short (as I understand) auto InterceptorKey runs now (after your upgrades):
- On startup
- On every Termux X11 execute

If the phone starts, it run InterceptorKey, it's on, but it doesn't work. But when I disable it, run Termux, and Termux X11 run then InterceptorKey, it works.

**Comment by twaik** [comment] 2023-08-08 20:13
As far as I know it should not start at device boot. I did not write such a behaviour. It should only be started when Termux:X11 activity starts...

**Comment by IntinteDAO** [comment] 2023-08-08 20:24
@twaik 

Yes, you are right. It looks like it's Android (Motorola?) that turns on all the features in recently used items. So if the KeyInterceptor was used by Termux X11 and not disabled, Android will run it at startup.

If this can be fixed, then presumably at startup Termux X11 would have to turn off the interceptor if auto start is enabled and turn it on.

**Comment by twaik** [comment] 2023-08-08 20:37
Actually I can do something that like.
Check it out.

[app-arm64-v8a-debug.zip](https://github.com/termux/termux-x11/files/12295647/app-arm64-v8a-debug.zip)

**Comment by IntinteDAO** [comment] 2023-08-08 20:45
@twaik Works!!

**Comment by twaik** [comment] 2023-08-08 20:46
I'll close the issue with commit...

**Closed** 2023-08-08 20:56 UTC
