### ISSUE TITLE
A issue about "Capture external mouse when possible" 

### ISSUE THREAD

**Issue by Rmtdi** [termux/termux-x11#421] opened 2023-08-09 03:43 UTC
I've looked at #403, but my issue isn't solved.

I downloaded the most recent build, but the mouse reversal issue persists.

Please help me＝＝

**Comment by twaik** [comment] 2023-08-09 04:44
No need to open new issue in the case if there is one opened.
Duplicate of #419

**Closed by twaik** 2023-08-09 04:44 UTC
