### ISSUE TITLE
vkcube framerate in latest version of termux-x11

### ISSUE THREAD

**Issue by hansm629** [termux/termux-x11#774] opened 2024-12-24 18:25 UTC
### Problem description

The latest version of `Termux-X11` has fixed all `X11 server` performance issues on `Samsung Exynos devices` using `ANGLE EGL`.

However, when running `vkcube`,
I noticed that it is showing an abnormally fast frame rate.

It is the same frame rate as when I added the `MESA_VK_WSI_PRESENT_MODE=mailbox` environment variable and ran it.

Is this the intended behavior?

If it is the intended behavior,
Is there an environment variable or option that can make it show the normal frame rate as before?

### What steps will reproduce the bug?

https://github.com/user-attachments/assets/a257114e-9893-4d80-a948-7d54998d65f3

**Comment by twaik** [comment] 2024-12-24 18:32
Can I please ask you to check which commit causes this? I mean checking artifacts in Actions tab.

**Comment by hansm629** [comment] 2024-12-24 18:40
@twaik 
https://github.com/termux/termux-x11/actions/runs/12476603692

I installed and tested the above version.

**Comment by twaik** [comment] 2024-12-24 18:42
It is the latest available version. 
It does not clarify which commit causes it.

**Comment by hansm629** [comment] 2024-12-24 18:46
@twaik 
Sorry.
I didn't understand correctly.

How can I explain it to you?

If you tell me the procedure, I will comment right away.

**Comment by twaik** [comment] 2024-12-24 18:47
I mean can you please check CI runs one by one in chronological order (probably starting with the artifact from two weeks ago) and tell me when the problem starts to be reproducible?

**Comment by hansm629** [comment] 2024-12-24 18:50
@twaik 
Oh! I understand now.
I will comment on which build the symptom occurred in after testing.

Please wait a moment.

**Comment by hansm629** [comment] 2024-12-24 19:05
@twaik 
I Found it!

The symptom occurs starting from the build below!

https://github.com/termux/termux-x11/actions/runs/12471770069

**Comment by twaik** [comment] 2024-12-24 19:08
It is sad. I will take a look at it later.
Can you please tell what vulkan implementation you use, where you got it (this exact version) and point to the source code of it?

**Comment by hansm629** [comment] 2024-12-24 19:14
@twaik 
https://github.com/termux/termux-packages/pull/22500

Tested on the latest build of `mesa-vulkan-icd-wrapper`, which is currently a pull request.

**Comment by twaik** [comment] 2024-12-29 05:26
@xMeM can you please take a look what exactly may go wrong?

**Comment by xMeM** [comment] 2024-12-29 07:34
https://github.com/termux/termux-x11/blob/2f4abe6445344551b8cb8bd2c1ecafefb2d82806/app/src/main/cpp/lorie/InitOutput.c#L867
It should be `Success` instead of `TRUE` ？

**Comment by twaik** [comment] 2024-12-29 08:03
You are right. I do not know how I missed it. 
Fixed by 0f95b0295bb7b5023d8bf2e5b98d5d020df480c3.

**Closed by twaik** 2024-12-29 08:03 UTC

**Comment by hansm629** [comment] 2024-12-30 13:12
@twaik 
Thank you! It's fixed!
And `vkmark` results are great too!

`X11 Server` on `Xclipse series GPU` is now perfect!


https://github.com/user-attachments/assets/26ca4ed6-0c4f-468c-9c73-8a3cc7589150

```
~$ vkmark
=======================================================
    vkmark 2017.08
=======================================================
    Vendor ID:      0x144D
    Device ID:      0x2600200
    Device Name:    Samsung Xclipse 940
    Driver Version: 8388608
    Device UUID:    35f18c726c2d5685ae5893b649517b92
=======================================================
[vertex] device-local=true: FPS: 5058 FrameTime: 0.198 ms
[vertex] device-local=false: FPS: 5289 FrameTime: 0.189 ms
[texture] anisotropy=0: FPS: 4952 FrameTime: 0.202 ms
[texture] anisotropy=16: FPS: 4858 FrameTime: 0.206 ms
[shading] shading=gouraud: FPS: 4877 FrameTime: 0.205 ms
[shading] shading=blinn-phong-inf: FPS: 4896 FrameTime: 0.204 ms
[shading] shading=phong: FPS: 4726 FrameTime: 0.212 ms
[shading] shading=cel: FPS: 4513 FrameTime: 0.222 ms
[effect2d] kernel=edge: FPS: 4167 FrameTime: 0.240 ms
[effect2d] kernel=blur: FPS: 3093 FrameTime: 0.323 ms
[desktop] <default>: FPS: 2321 FrameTime: 0.431 ms
[cube] <default>: FPS: 3751 FrameTime: 0.267 ms
[clear] <default>: FPS: 4202 FrameTime: 0.238 ms
=======================================================
                                   vkmark Score: 4361
=======================================================
```

**Comment by twaik** [comment] 2024-12-30 13:14
Hight result is probably because of dropping the frames which are not going to be displayed. So the driver works correctly.
