### ISSUE TITLE
Mod4 key not working with external keyboard + some suggestions

### ISSUE THREAD

**Issue by human-V-oid** [termux/termux-x11#47] opened 2021-10-09 00:53 UTC
I've been using Termux-X11 to get a GUI in proot-distro archlinux, mainly I use qtile window manager
Recently I purchased an external keyboard, and observed that the Mod4 key or the command/Windows key is not being captured by Termux-X11, and the same happens with Xserver-XSDL
Any ideas for how to get it work

Also If the Termux-X11 app had a setting for keeping 4:3 screen aspect ratio as in Xserver-XSDL and had a full-screen mode (showing the notch), It'd be awesome🙂

Keep up the great work, and have a nice day

**Comment by xu3s** [comment] 2021-10-09 03:00
Also i notice that shift key is flickering if used for example mark multiple file in file manager with shift+click it doesn't register, and i tried gimp and notice that when i press shift key it flickering. But doing fine when used to type in terminal

**Comment by twaik** [comment] 2021-10-09 17:09
Hi. We have problems with keyboard capturing because of Android restrictions. Android does not allow applications to capture some keys and key combinations (like Mod, Alt+Tab, etc.). I do not think it can be fixed but we I am hardly trying. Thank you.

**Comment by human-V-oid** [comment] 2021-10-10 02:03
> Hi. We have problems with keyboard capturing because of Android restrictions. Android does not allow applications to capture some keys and key combinations (like Mod, Alt+Tab, etc.). I do not think it can be fixed but we I am hardly trying. Thank you.

All keys work properly with Hacker's i.e. a soft keyboard though

Alt works as intended, but Alt+Tab brings recents menu 

Earlier the Mod key woke Google Assistant up but I turned it off in the settings, But Mod key still does not work

Yes, Android has become really a lot restricting, and I guess they plan to take developer freedom bit by bit in the future, as they have the competition with iOS :D
Kinda miss the Android 5 days

**Comment by zanfix** [comment] 2022-01-25 16:33
Microsoft's "Remote Desktop" android app (RD Client) is able to capture ALT+TAB!

**Comment by twaik** [comment] 2022-07-05 15:12
@zanfix Does it capture Alt+Tab on Samsung devices only?

**Comment by zanfix** [comment] 2022-07-05 23:25
> @zanfix Does it capture Alt+Tab on Samsung devices only?

Mmmh, can not say, i only have samsung devices (with dex)

**Comment by twaik** [comment] 2022-08-02 06:27
@human-V-oid Do you have Samsung device? I can try to use [`SamsungDexUtils.kt`](https://github.com/iiordanov/remote-desktop-clients/blob/8088b4411cb5e051eb3b2491789227dbea251524/bVNC/src/main/java/com/iiordanov/util/SamsungDexUtils.kt) to make Mod4 and other keys work on your device.

**Comment by human-V-oid** [comment] 2022-08-02 07:17
> @human-V-oid Do you have Samsung device? I can try to use [`SamsungDexUtils.kt`](https://github.com/iiordanov/remote-desktop-clients/blob/8088b4411cb5e051eb3b2491789227dbea251524/bVNC/src/main/java/com/iiordanov/util/SamsungDexUtils.kt) to make Mod4 and other keys work on your device.

No, I don't, but it may help people who have one.

**Comment by twaik** [comment] 2023-02-01 16:53
@zanfix can you please check if it works on your Dex-compatible device?

**Comment by zanfix** [comment] 2023-02-06 23:03
> @zanfix can you please check if it works on your Dex-compatible device?

Yes it works!
Alt + Tab, Super_L + <...>, and Alt + F4 all works on my box!

The only thing I noticed is that F1 is received, but DEX still show the android shortcut window.

**Comment by twaik** [comment] 2023-02-09 20:23
Capturing special keys always was restricted so capturing them on DEX is some kind of miracle.

**Comment by twaik** [comment] 2023-03-02 14:00
@human-V-oid I realized that Mod4 is not a Meta button... And I do not really know where to find it on my keyboard. Can you please try latest build, enabling "Intercept system shortcuts" in preferences?

**Comment by twaik** [comment] 2023-03-02 14:01
@human-V-oid you can find latest build [here](https://github.com/twaik/termux-x11/actions).

**Comment by human-V-oid** [comment] 2023-03-02 21:11
> @human-V-oid I realized that Mod4 is not a Meta button... And I do not really know where to find it on my keyboard.

Mod4 key is the Windows key, which can be found between Ctrl and Alt keys.

> Can you please try latest build, enabling "Intercept system shortcuts" in preferences?

Yes, I tried the build, but the issue persists as I am not using a DeX compatible device.

**Comment by twaik** [comment] 2023-03-02 21:15
I thought mod4 is something like modifier.

**Comment by human-V-oid** [comment] 2023-03-04 16:17
> I thought mod4 is something like modifier.

Of course, it is a modifier key.

**Comment by twaik** [comment] 2023-03-04 16:23
I meant I thought you're tasking about compose key.

**Comment by human-V-oid** [comment] 2023-03-04 16:28
Is that the Fn key? I've never seen a keyboard with a key labeled 'compose'.

**Comment by twaik** [comment] 2023-03-04 16:29
Not Fn. [Link](https://help.ubuntu.com/community/ComposeKey).

**Comment by twaik** [comment] 2023-03-04 17:24
I think so. But not sure.

**Comment by twaik** [comment] 2023-03-06 20:10
I think it is not fixed until I make it work with non-Dex devices too.

**Comment by twaik** [comment] 2023-03-07 00:28
@human-V-oid I can make it intercept all keys of external keyboard with some root or adb command, will it fit you?

**Comment by human-V-oid** [comment] 2023-03-07 04:52
> @human-V-oid I can make it intercept all keys of external keyboard with some root or adb command, will it fit you?

Root will be fine, and with adb it would be even nicer

Although I don't use Termux regularly nowadays, I'm sure the fix will help some people, and me when I need to do something on the fly.

**Comment by twaik** [comment] 2023-05-25 05:19
Fixed by https://github.com/termux/termux-x11/commit/ee2224e474ce0c184de7a2c9c454c658f8afe249.

**Closed** 2023-05-25 05:22 UTC
Labels: bug, enhancement

**Comment by stylustrader** [comment] 2024-05-26 22:46
Hi 
I'm using the latest build but it seems that as soon as I enter dex mode, mod4 key pressed are not captured by x11. System keyboard shortcuts still work on x11 session.
In non-dex mode, (screen mirroring) it works fine. Mod4 keys are correctly captured. Can you try to reproduce? @zanfix @human-V-oid @twaik
